---this config file was auto-generated by Excel2lua tool, do not modify it!

local config = {
["str_ui_story_cancel"]="取消", ["str_ui_story_skip"]="跳过", ["str_ui_story_autoSign"]="AUTO", ["str_ui_story_skipSign"]="SKIP", ["str_ui_story_second"]="秒", ["str_ui_story_Title"]="剧情梗概", }
return config