---this config file was auto-generated by Excel2lua tool, do not modify it!

local config = {
["str_ui_task_tip"]="提示", ["str_ui_task_title"]="是否放弃以下任务？", ["str_ui_task_cancel"]="取消", ["str_ui_task_do"]="确定", ["str_ui_task_warn"]="放弃任务会清除当前已完成的进度，可重新接取", ["str_ui_task_main"]="主线任务", ["str_ui_task_branch"]="支线任务", }
return config