---this config file was auto-generated by Excel2lua tool, do not modify it!

local config = {
["str_character_name_main"]="宏泽", ["str_character_desc_main"]="宏泽", ["str_character_name_1"]="灵雨", ["str_character_desc_1"]="节制", ["str_character_story_1"]="TARO行动队队长，富有正义感的少女。被TARO栽培长大，一直以来都没有放弃寻找失踪的哥哥，有着坚定的目标。在事件中总能保持理智的分析和冷静的判断，也被众人视为值得信赖的队友。TARO行动队队长，富有正义感的少女。被TARO栽培长大，一直以来都没有放弃寻找失踪的哥哥，有着坚定的目标。在事件中总能保持理智的分析和冷静的判断，也被众人视为值得信赖的队友。TARO行动队队长，富有正义感的少女。被TARO栽培长大，一直以来都没有放弃寻找失踪的哥哥，有着坚定的目标。在事件中总能保持理智的分析和冷静的判断，也被众人视为值得信赖的队友。TARO行动队队长，富有正义感的少女。被TARO栽培长大，一直以来都没有放弃寻找失踪的哥哥，有着坚定的目标。在事件中总能保持理智的分析和冷静的判断，也被众人视为值得信赖的队友。", ["str_character_name_2"]="耀", ["str_character_desc_2"]="太阳", ["str_character_story_2"]="中学二年级在读中，心里住着一个勇者，一直坚信自己可以拯救世界。十分看重与朋友的关系，虽然有时候冒冒失失，但也能敏感察觉到别人的心情，呵护着朋友的自尊心。", ["str_character_name_3"]="千世", ["str_character_desc_3"]="世界", ["str_character_story_3"]="充满活力的中学少女，长相可爱，在同学中很受欢迎，同时也是松月高中的啦啦队员。有时候会一针见血地指出问题，而展露出外表之外的成熟。", ["str_character_name_4"]="祐希", ["str_character_desc_4"]="星星", ["str_character_story_4"]="温柔的邻家少女", ["str_skin_name_main"]="宏泽", ["str_skin_name_1_0"]="灵雨", ["str_skin_name_1_1"]="灵雨", ["str_skin_name_2_0"]="耀", ["str_skin_name_2_1"]="耀", ["str_skin_name_3_0"]="千世", ["str_skin_name_3_1"]="千世", ["str_skin_name_4_0"]="祐希", ["str_skin_name_4_1"]="祐希", ["str_character_class_carryout"]=[[7号-输出
后手|负面]], ["str_character_class_resonance"]=[[6号-共鸣
先手|负面]], ["str_character_class_helper"]="9号辅助", ["str_character_class_01"]="输出", ["str_character_class_02"]="共鸣", ["str_character_class_03"]="辅助", ["str_character_class_04"]="先手", ["str_character_class_05"]="后手", ["str_character_class_06"]="减耗", ["str_character_class_07"]="治疗", ["str_character_class_08"]="追击", ["str_character_class_09"]="必杀", ["str_character_class_10"]="溅射", ["str_character_class_11"]="耗尽", ["str_character_class_12"]="回能", ["str_character_class_13"]="暗伤", ["str_character_class_14"]="暴击", ["str_character_class_15"]="嘲讽", ["str_character_class_16"]="增伤", ["str_character_class_17"]="减冷却", ["str_character_class_18"]="附加生命", ["str_character_class_19"]="普攻", ["str_character_class_20"]="负面", ["str_character_class_21"]="频率", ["str_character_class_22"]="克制", ["str_character_class_23"]="注能", ["str_character_class_24"]="刺痕", ["str_character_class_25"]="齐心", ["str_character_class_26"]="传递", ["str_character_class_27"]="递增", ["str_character_class_28"]="终结", ["str_character_class_29"]="节奏", ["str_character_class_30"]="无消耗", ["str_character_class_31"]="延缓攻击", ["str_character_class_0100"]=[[输出
(不重复)]], ["str_character_class_0101"]=[[13号-共鸣
先手|耗尽]], ["str_character_class_0102"]=[[11号-共鸣
先手|回能]], ["str_character_class_0103"]=[[12号-输出
后手|普攻]], ["str_character_class_0104"]=[[11号-共鸣
先手|频率]], ["str_character_class_0105"]=[[10号-共鸣
先手|克制]], ["str_character_class_0106"]=[[1-输出
（溅射）]], ["str_character_class_0107"]=[[5号-输出
后手|必杀]], ["str_character_class_0108"]=[[4号-共鸣
先手|暗伤]], ["str_character_class_0109"]=[[3号-输出
后手|冷却]], ["str_character_class_0110"]=[[2号-共鸣
先手|减耗]], ["str_character_class_0111"]=[[21号-输出
后手|暴击]], ["str_character_class_0112"]=[[22号-输出
后手|生命]], ["str_character_class_0113"]=[[1号-输出
后手|反击]], ["str_character_in_battle"]="已上阵", ["str_character_less_role"]="请选满6个角色再开始战斗", ["str_character_class_carryout2"]=[[9号-输出
后手|必杀]], ["str_character_class_resonance2"]=[[8号-共鸣
先手|必杀]], ["str_character_class_0114"]=[[CE-输出
后手|追击]], ["str_character_class_0115"]=[[CE-共鸣
先手|减耗]], ["str_character_class_0116"]="CE-辅助", ["str_character_class_0117"]=[[CE-输出
后手|溅射]], ["str_character_class_0118"]=[[CE-共鸣
先手|增伤]], ["str_character_class_0119"]=[[14号-输出
后手|注能]], ["str_character_class_0120"]=[[15号-输出
后手|刺痕]], ["str_character_class_0121"]=[[16号-输出
后手|齐心]], ["str_character_class_0122"]=[[17号-共鸣
先手|传递]], ["str_character_class_0123"]=[[18号-共鸣
先手|递增]], ["str_character_class_0124"]=[[19号-共鸣
先手|终结]], ["str_character_class_0125"]=[[20号-共鸣
先手|节奏]], ["str_character_class_0126"]=[[23号-辅助
增加hit]], ["str_character_class_0127"]=[[24号-辅助
延迟蓄力]], ["str_character_name_5"]="柯锡丝", ["str_character_name_6"]="耐鲁", ["str_character_name_7"]="太阳-输出", ["str_character_name_8"]="节制-共鸣", ["str_character_name_9"]="世界-输出", ["str_character_name_10"]="世界-输出A变身", ["str_character_name_11"]="耐鲁-共鸣", ["str_character_name_12"]="耐鲁-共鸣A变身", ["str_character_name_13"]="世界-宇宙", ["str_character_name_14"]="节制-共鸣", ["str_character_name_15"]="柯锡-回能", ["str_character_name_16"]="耐鲁-输出", ["str_character_name_17"]="星星-共鸣", ["str_character_name_18"]="太阳-共鸣", ["str_character_name_19"]="节制-输出", ["str_character_name_20"]="太阳-输出", ["str_character_name_21"]="世界-共鸣", ["str_character_name_22"]="柯锡-输出", ["str_character_name_23"]="耐鲁-共鸣", ["str_character_name_24"]="节制-输出", ["str_character_name_25"]="世界-输出", ["str_character_name_26"]="太阳-输出", ["str_character_name_27"]="世界-输出", ["str_character_name_28"]="太阳-共鸣", ["str_character_name_29"]="星星-辅助", ["str_character_name_30"]="节制-输出", ["str_character_name_31"]="耐鲁-共鸣", ["str_character_name_32"]="太阳-输出", ["str_character_name_33"]="节制-输出", ["str_character_name_34"]="世界-输出", ["str_character_name_35"]="耐鲁-共鸣", ["str_character_name_36"]="柯锡-共鸣", ["str_character_name_37"]="太阳-共鸣", ["str_character_name_38"]="节制-共鸣", ["str_character_name_39"]="星星-辅助", ["str_character_name_40"]="节制-辅助", }
return config