---this config file was auto-generated by Excel2lua tool, do not modify it!

local config = {
["str_tutorial_btn_name"]="教程功能", ["str_tutorial_btn_tip"]="TUTORIAL FUNCTION", ["str_tutorial_name1"]="鸟瞰点", ["str_tutorial_name2"]="宝箱", ["str_tutorial_name3"]="广告牌", ["str_tutorial_name4"]="电水洼", ["str_tutorial_name5"]="电箱", ["str_tutorial_name6"]="移动平台", ["str_tutorial_des1"]="抵达鸟瞰点后，可以眺望附近的区域，并在小地图中获取更多的信息。", ["str_tutorial_des2"]="地图中的宝箱，打开后可能会有意想不到的收获。", ["str_tutorial_des3"]="道路中竖立的广告牌，也可以成为新的通路。", ["str_tutorial_des4"]="角色在充满电力的水洼中无法正常前行，需要先找到机关后才能通过。", ["str_tutorial_des5"]="关闭所有的电箱后，角色便可以正常通过电水洼所在的区域。", ["str_tutorial_des6"]="被特殊力量侵蚀的平台在漂浮移动，或许可以带领角色前往新的区域。", }
return config