---this config file was auto-generated by Excel2lua tool, do not modify it!

local config = {
["str_ui_demo_main_controller_1"]="测试UI", ["str_ui_demo_main_controller_2"]="测试通用过程", ["str_ui_demo_main_controller_3"]="测试状态机", ["str_ui_demo_main_controller_4"]="测试时间轴", ["str_ui_demo_story_controller_1"]="跳过", ["str_ui_demo_story_speaker_name_1"]="临空者号", ["str_ui_demo_story_speak_content_1"]="这位光灵果然不同凡响。你们的配合也很默契！", }
return config