---this config file was auto-generated by Excel2lua tool, do not modify it!

local config = {
["str_monster_name_2700011"]="Envy", ["str_monster_des_2700011"]="最常见的怪物，游荡在城市各个地方，没有什么特殊的能力", ["str_monster_name_2700021"]="Angry", ["str_monster_des_2700021"]=[[能力1：偷取行动值。

能力2：周期标记敌方，并在下次攻击时造成高额伤害。]], ["str_monster_name_2700031"]="Lie", ["str_monster_des_2700031"]=[[能力1：自身获得<color=#ff3a3a>「护盾」</color>。

能力2：降低敌方的行动值上限。

<color=#ff3a3a>「护盾」</color>可以抵挡若干次打击，一次连招未击破则护盾刷新。]], ["str_monster_name_2700041"]="Complain", ["str_monster_des_2700041"]=[[能力：对目标附加<color=#ff3a3a>「技能腐蚀」</color>，使其持续损失生命。

<color=#ff3a3a>「技能腐蚀」</color>腐蚀一个技能，使其持续损失生命，释放此技能后结束腐蚀。]], ["str_monster_name_2800051"]="Hate", ["str_monster_des_2800051"]=[[能力1：降低敌方的行动值上限。
能力2：自身获得<color=#ff3a3a>「护盾」</color>，护盾存在期间攻击大幅提高。

<color=#ff3a3a>「护盾」</color>可以抵挡若干次打击，一次连招未击破则护盾刷新。]], ["str_monster_name_2800061"]="Greed", ["str_monster_des_2800061"]=[[能力：自身获得<color=#ff3a3a>「护盾」</color>，护盾存在期间释放强力技能。

<color=#ff3a3a>「护盾」</color>可以抵挡若干次打击，一次连招未击破则护盾刷新。]], ["str_monster_name_2710011"]="Envy", ["str_monster_des_2710011"]="常见的怪物，会成群结队出现", ["str_monster_name_2730031"]="Envy[士兵]", ["str_monster_des_2730031"]=[[能力1：集火攻击指挥官标记的敌人
能力2：两个士兵攻击同一目标时，对主目标及两侧敌人造成爆炸伤害]], ["str_monster_name_2730061"]="Complain[狂暴]", ["str_monster_des_2730061"]="能力：敌方有角色血量降低至最大值50%以下时，极大提高自身行动速度", ["str_monster_name_2710021"]="Angry", ["str_monster_des_2710021"]=[[能力1：一次连招内受到10次打击后，将免疫后续伤害。
能力2：每受到1次打击，下一次攻击伤害都会小幅提升]], ["str_monster_name_2730011"]="Angry", ["str_monster_des_2730011"]=[[能力1：一次连招内受到10次打击后，将免疫后续伤害。
能力2：每受到1次打击，下一次攻击伤害都会小幅提升
能力3：生命值下降到10%时，将暂时免疫后续伤害，并将受到的伤害转化为治疗]], ["str_monster_name_2710031"]="Lie[吸能]", ["str_monster_des_2710031"]="能力：受到打击时，减少攻击者获得的必杀能量。", ["str_monster_name_2710032"]="Lie[封锁]", ["str_monster_des_2710032"]="能力：降低敌方的行动值上限。", ["str_monster_name_2710033"]="Lie[流血]", ["str_monster_des_2710033"]=[[能力：对敌方全体造成<color=#ff3a3a>「流血」</color>。

<color=#ff3a3a>「流血」</color>持续损失生命，效果可叠加。]], ["str_monster_name_2730021"]="Lie[指挥官]", ["str_monster_des_2730021"]=[[能力1：指挥士兵集火攻击1个敌人
能力2：<color=#ff3a3a>「避难」</color>时让士兵替自身承受全部伤害]], ["str_monster_name_2730041"]="Lie[洞察]", ["str_monster_des_2730041"]=[[能力1：使攻击目标<color=#ff3a3a>「洞察」</color>自身一个弱点
能力2：蓄力过程中被<color=#ff3a3a>「洞察」</color>自身弱点的角色攻击将会降低该技能造成的伤害]], ["str_monster_name_2710041"]="Complain[腐蚀]", ["str_monster_des_2710041"]=[[能力：对目标附加<color=#ff3a3a>「技能腐蚀」</color>。

<color=#ff3a3a>「技能腐蚀」</color>腐蚀一个技能，技能持有者将持续损失生命，释放此技能后清除腐蚀。]], ["str_monster_name_2720041"]="Complain[反伤][腐蚀]", ["str_monster_des_2720041"]=[[能力1：受到非克制攻击时，反弹伤害。
能力2：对目标附加<color=#ff3a3a>「技能腐蚀」</color>。

<color=#ff3a3a>「技能腐蚀」</color>腐蚀一个技能，技能持有者将持续损失生命，释放此技能后清除腐蚀。]], ["str_monster_name_2730051"]="Complain[防御切换][嘲讽]", ["str_monster_des_2730051"]=[[能力1：防御能力周期性切换，交替免疫<color=#ff3a3a>多hit</color>或<color=#ff3a3a>少hit</color>伤害
能力2：强制敌方全体攻击自己]], ["str_monster_name_2810051"]="Hate", ["str_monster_des_2810051"]=[[能力1：降低敌方的行动值上限。
能力2：自身获得<color=#ff3a3a>「护盾」</color>，护盾存在期间攻击大幅提高。

<color=#ff3a3a>「护盾」</color>可以抵挡15次打击，一次连招未击破则护盾刷新。]], ["str_monster_name_2810061"]="Greed[激怒]", ["str_monster_des_2810061"]="能力：一次连招内受到10次打击后，将被激怒并释放强力技能。", ["str_monster_name_2810062"]="Greed[护盾]", ["str_monster_des_2810062"]=[[能力：自身获得<color=#ff3a3a>「护盾」</color>，护盾存在期间释放强力技能。

<color=#ff3a3a>「护盾」</color>可以抵挡15次打击，一次连招未击破则护盾刷新。]], ["str_monster_name_2820062"]="Greed[反伤][护盾]", ["str_monster_des_2820062"]=[[能力1：受到非克制攻击时，反弹伤害。
能力2：自身获得<color=#ff3a3a>「护盾」</color>，护盾存在期间释放强力技能。

<color=#ff3a3a>「护盾」</color>可以抵挡15次打击，一次连招未击破则护盾刷新。]], }
return config