---this config file was auto-generated by Excel2lua tool, do not modify it!

local config = {
["str_mainstory_1_1_999_1_6"]="灵雨姐的……哥哥吗？", ["str_mainstory_1_1_999_1_5"]="不过，可以理解，我哥哥像耀这个年纪的时候也很喜欢这些。", ["str_mainstory_1_1_999_1_4"]="但，这可是假面骑士的限定款欸，很难买到！", ["str_mainstory_1_1_999_1_3"]="耀加入小队这么久，还是像小孩子一样喜欢这些。", ["str_mainstory_1_1_999_1_2"]="没关系的，刚刚在等灵雨姐的时候，买到了假面骑士限定扭蛋，超幸运的！", ["str_mainstory_1_1_999_1_1"]="等很久了吧，刚刚因为紧急任务耽误了一些时间。", ["str_mainstory_1_1_999_6_1"]="随便说点啥", ["str_mainstory_1_1_999_6_2"]="的东西密度较高", }
return config