---this config file was auto-generated by Excel2lua tool, do not modify it!

local config = {
["ui_pet_tag_friend_1"]="启光将军", ["ui_pet_tag_friend_2"]="支援本部", ["ui_pet_tag_friend_3"]="科研室", ["ui_pet_tag_friend_4"]="四天使", ["ui_pet_tag_friend_5"]="高庭", ["ui_pet_tag_friend_6"]="审判庭", ["ui_pet_tag_friend_7"]="学院诗班", ["ui_pet_tag_friend_8"]="伊斯塔万帮", ["ui_pet_tag_friend_9"]="影镇的独行者", ["ui_pet_tag_friend_10"]="北境宫廷", ["ui_pet_tag_friend_11"]="第一派系", ["ui_pet_tag_friend_12"]="亡命阵列", ["ui_pet_tag_friend_13"]="红油扳手音乐节", ["ui_pet_tag_friend_14"]="金丝雀与野斑鸠", ["ui_pet_tag_friend_15"]="信使公会", ["ui_pet_tag_friend_16"]="奴仆暗鬼", ["ui_pet_tag_friend_17"]="猎灵暗鬼", ["ui_pet_tag_friend_18"]="异邪暗鬼", ["ui_pet_tag_friend_19"]="日蚀仆从", }
return config