//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TestLuaCsFunctionWarpperWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(TestLuaCsFunctionWarpper), typeof(System.Object));
		L.RegFunction("LuaToCsTest", LuaToCsTest);
		L.RegFunction("New", _CreateTestLuaCsFunctionWarpper);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateTestLuaCsFunctionWarpper(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				TestLuaCsFunctionWarpper obj = new TestLuaCsFunctionWarpper();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: TestLuaCsFunctionWarpper.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int LuaToCsTest(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 0);
			TestLuaCsFunctionWarpper.LuaToCsTest();
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

