---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Name=2, TitleID=3, ContentID=4, MailType=5, Intro=6, Appendix=7, }
local config = {
{1, "经验邮件", 1, 1, 2, "赠送玩家500点经验", {{1,500,}, }, },
[8866]={8866, "测试邮件", 3, 3, 2, "啥也不送", },
{2, "经验金币邮件", 2, 2, 2, "赠送玩家500点经验及1000金币", {{1,500,}, {2,1000,}, }, },
{3, "测试邮件", 4, 4, 2, "啥也不送", },
{4, "测试邮件", 4, 4, 2, "啥也不送", },
}
return config, 'ID', key