---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Break=2, Name=3, SectionType=4, Desc=5, ActorType=6, ActorID=7, ActorSkin=8, SceneName=9, HideEventObject=10, StartOrEnd=11, NextSection=12, CanSkip=13, OptionWord1=14, OptionNextSection1=15, OptionWord2=16, OptionNextSection2=17, OptionWord3=18, OptionNextSection3=19, OptionWord4=20, OptionNextSection4=21, BlackScreenBeforeStart=22, BlackScreenDuringTimer=23, BlackScreenBeforeEnd=24, }
local commonData = {{1, 1, 1, 1, }, {100000001, 100000002, 100000005, 100000006, }, {110010001, 110020001, 110050001, 110060001, }, }
local config = {
{1, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 3, -1, 0, "嗯，轻小说浓度过高。", 2, nil, 0, nil, 0, nil, 0, },
{2, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 0, 3, 0, nil, 0, nil, 0, nil, 0, nil, 0, nil, nil, "0;300", },
{3, 0, "屏幕遮罩", 2, "绫人出现", nil, nil, nil, "200011", nil, 0, 4, 0, nil, 0, nil, 0, nil, 0, nil, 0, nil, "0;1000", },
{4, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, "这就是我们的任务。 ", 5, "我明白了。 ", 5, nil, 0, nil, 0, "0;200", },
{5, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
}
return config, 'ID', key