---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Break=2, Name=3, SectionType=4, Desc=5, ActorType=6, ActorID=7, ActorSkin=8, SceneName=9, HideEventObject=10, StartOrEnd=11, NextSection=12, CanSkip=13, OptionWord1=14, OptionNextSection1=15, OptionWord2=16, OptionNextSection2=17, OptionWord3=18, OptionNextSection3=19, OptionWord4=20, OptionNextSection4=21, BlackScreenBeforeStart=22, BlackScreenDuringTimer=23, BlackScreenBeforeEnd=24, }
local commonData = {{1, }, {100000003, }, {110030001, }, }
local config = {
{1, 0, "选择", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 3, -1, 1, "动作", 2, "表情", 3, "点头摇头", 4, nil, 0, },
{2, 0, "选择镜头", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 1, "正面", 5, "右前侧", 7, "左前侧", 6, nil, 0, },
{3, 0, "表情", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{4, 0, "点头摇头", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{5, 0, "正面动作", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{6, 0, "左前侧动作", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{7, 0, "右前侧动作", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
}
return config, 'ID', key