---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Break=2, Name=3, SectionType=4, Desc=5, ActorType=6, ActorID=7, ActorSkin=8, SceneName=9, HideEventObject=10, StartOrEnd=11, NextSection=12, CanSkip=13, OptionWord1=14, OptionNextSection1=15, OptionWord2=16, OptionNextSection2=17, OptionWord3=18, OptionNextSection3=19, OptionWord4=20, OptionNextSection4=21, BlackScreenBeforeStart=22, BlackScreenDuringTimer=23, BlackScreenBeforeEnd=24, }
local commonData = {{1, 1, 1, 1, }, {100000001, 100000003, 100000004, 100000006, }, {110010001, 110030001, 110040001, 110060001, }, }
local config = {
{1, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 3, -1, 0, "节制", 2, "世界", 3, "星星", 4, "耐鲁", 5, },
{2, 0, "节制", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, "动作", 6, "表情", 7, nil, 0, nil, 0, },
{3, 0, "世界", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, "世界动作", 8, "世界表情", 9, nil, 0, nil, 0, },
{4, 0, "星星", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, "动作", 10, "表情", 11, nil, 0, nil, 0, },
{5, 0, "耐鲁", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, "耐鲁动作", 12, "耐鲁表情", 13, nil, 0, nil, 0, },
{6, 0, "节制动作", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, "结束", 14, "还看节制", 2, "看其他角色", 1, nil, 0, },
{7, 0, "节制表情", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, "结束", 14, "还看节制", 2, "看其他角色", 1, nil, 0, },
{8, 0, "世界动作", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, "结束", 14, "还看世界", 3, "看其他角色", 1, nil, 0, },
{9, 0, "世界表情", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, "结束", 14, "看其他角色", 1, "还看世界", 3, nil, 0, },
{10, 0, "星星动作", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, "结束", 14, "还看星星", 4, "看其他角色", 1, nil, 0, },
{11, 0, "星星表情", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, "结束", 14, "还看星星", 4, "看其他角色", 1, nil, 0, },
{12, 0, "耐鲁动作", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, "结束", 14, "还看耐鲁", 5, "看其他角色", 1, nil, 0, },
{13, 0, "耐鲁表情", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, "结束", 14, "还看耐鲁", 5, "看其他角色", 1, nil, 0, },
{14, 0, "结束", 1, nil, commonData[1], commonData[2], commonData[3], "200011", "None", 2, -1, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
}
return config, 'ID', key