---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Break=2, Name=3, SectionType=4, Desc=5, ActorType=6, ActorID=7, ActorSkin=8, SceneName=9, HideEventObject=10, StartOrEnd=11, NextSection=12, CanSkip=13, OptionWord1=14, OptionNextSection1=15, OptionWord2=16, OptionNextSection2=17, OptionWord3=18, OptionNextSection3=19, OptionWord4=20, OptionNextSection4=21, BlackScreenBeforeStart=22, BlackScreenDuringTimer=23, BlackScreenBeforeEnd=24, }
local commonData = {{1, 1, 1, }, {100000001, 100000003, 100000004, }, {110010001, 110030001, 110040001, }, }
local config = {
{1, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 1, 2, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{2, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 3, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{3, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 4, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{4, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 5, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{5, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 6, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{6, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 7, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{7, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 8, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{8, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 9, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{9, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 10, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{10, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 11, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{11, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 12, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{12, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 13, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{13, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 14, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{14, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 15, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{15, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 16, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{16, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 17, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{17, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 18, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{18, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 19, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{19, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 20, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{20, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 21, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{21, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 22, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{22, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 0, 23, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
{23, 0, nil, 1, nil, commonData[1], commonData[2], commonData[3], "200011", "All", 2, -1, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
}
return config, 'ID', key