---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Break=2, Name=3, SectionType=4, Desc=5, ActorType=6, ActorID=7, ActorSkin=8, SceneName=9, HideEventObject=10, StartOrEnd=11, NextSection=12, CanSkip=13, OptionWord1=14, OptionNextSection1=15, OptionWord2=16, OptionNextSection2=17, OptionWord3=18, OptionNextSection3=19, OptionWord4=20, OptionNextSection4=21, BlackScreenBeforeStart=22, BlackScreenDuringTimer=23, BlackScreenBeforeEnd=24, }
local commonData = {{1, 1, 1, 1, }, {100000005, 100000001, 100000002, 100000006, }, {110050001, 110010001, 110020001, 110060001, }, {100000005, 100000002, 100000001, 100000006, }, {110050001, 110020001, 110010001, 110060001, }, }
local config = {
[4]={4, 0, "出场前", 1, "出场剧情1", commonData[1], commonData[2], commonData[3], "200011", "All", 1, 5, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
[5]={5, 0, "选项", 1, "剧情选项", commonData[1], commonData[2], commonData[3], "200011", "All", 2, -1, 0, "嗯，「轻小说浓度过高」。", 7, nil, 0, nil, 0, nil, 0, },
[7]={7, 0, "选项后", 1, nil, commonData[1], commonData[4], commonData[5], "200011", "All", 0, 8, 0, nil, 0, nil, 0, nil, 0, nil, 0, nil, nil, "0;500", },
[8]={8, 0, "屏幕遮罩", 2, "绫人向我们走了过来……", nil, nil, nil, "200011", nil, 0, 14, 0, nil, 0, nil, 0, nil, 0, nil, 0, nil, "0;3000", },
[14]={14, 0, "出场后", 1, "凌人出场后", commonData[1], commonData[2], commonData[3], "200011", "All", 0, 15, 0, nil, 0, nil, 0, nil, 0, nil, 0, "0;500", },
[15]={15, 0, "段落", 1, "选项", commonData[1], commonData[2], commonData[3], "200011", "All", 2, -1, 0, "这就是我们的任务。", 16, "我明白了。", 16, nil, 0, nil, 0, },
[16]={16, 0, "选项后11", 1, nil, commonData[1], commonData[4], commonData[5], "200011", "All", 2, -1, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
}
return config, 'ID', key