---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Break=2, Name=3, SectionType=4, Desc=5, ActorType=6, ActorID=7, ActorSkin=8, SceneName=9, HideEventObject=10, StartOrEnd=11, NextSection=12, CanSkip=13, OptionWord1=14, OptionNextSection1=15, OptionWord2=16, OptionNextSection2=17, OptionWord3=18, OptionNextSection3=19, OptionWord4=20, OptionNextSection4=21, BlackScreenBeforeStart=22, BlackScreenDuringTimer=23, BlackScreenBeforeEnd=24, }
local config = {
{1, 0, "测试剧情", 1, "测试", {1, 1, }, {100000001, 100000002, }, {110010001, 110020001, }, "200011", "All", 3, -1, 0, nil, 0, nil, 0, nil, 0, nil, 0, },
}
return config, 'ID', key