---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Triggers=2, InterActType=3, Name=4, Des=5, Icon=6, }
local config = {
{1, 1, nil, "str_tutorial_name1", {"str_tutorial_des1", }, {"ui_fuben_wanfa_neirong_ditujiesuodian", }, },
{2, 1, 3, "str_tutorial_name2", {"str_tutorial_des2", }, {"ui_fuben_wanfa_neirong_baoxiang", }, },
{3, 1, nil, "str_tutorial_name3", {"str_tutorial_des3", }, {"ui_fuben_wanfa_neirong_gaunggaopai", }, },
{4, 1, nil, "str_tutorial_name4", {"str_tutorial_des4", "str_tutorial_des5", }, {"ui_fuben_wanfa_neirong_dianshuiwa", "ui_fuben_wanfa_neirong_dianxiang", }, },
{5, 1, nil, "str_tutorial_name5", {"str_tutorial_des5", }, {"ui_fuben_wanfa_neirong_dianxiang", }, },
{6, 1, nil, "str_tutorial_name6", {"str_tutorial_des6", }, {"ui_fuben_wanfa_neirong_fudongpingtai", }, },
}
return config, 'ID', key