---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, EventID=2, EventPos=3, TaskTitle=4, TaskContent=5, TaskPillar=6, TaskRout=7, IsShowDistance=8, }
local config = {
{1, 102500000, nil, nil, nil, nil, nil, true, },
{2, 102500001, },
}
return config, 'ID', key