---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, EventType=2, EventTriggerType=3, Des=4, CorrelationIDs=5, EventTriggerConditionGroupID=6, EventActiveConditionGroupID=7, EventCompleteConditionGroupID=8, MapElementID=9, EventReward=10, ForcedShow=11, }
local config = {
[102500000]={102500000, 1, 1, "出生点", 0, nil, nil, nil, nil, nil, false, },
[102500001]={102500001, 5, 2, "胜利点", 0, nil, nil, nil, nil, nil, false, },
[102500002]={102500002, 2, 2, "战斗1_眺望点附近", 102500002, nil, nil, nil, nil, nil, true, },
[102500003]={102500003, 2, 2, "战斗2_", 102500003, nil, nil, nil, nil, nil, true, },
[102500004]={102500004, 2, 2, "战斗3_精英", 102500004, nil, nil, nil, nil, nil, true, },
[102500005]={102500005, 2, 2, "战斗4", 102500005, nil, nil, nil, nil, nil, true, },
[102500006]={102500006, 2, 2, "战斗5", 102500006, nil, nil, nil, nil, nil, true, },
[102500007]={102500007, 2, 2, "战斗6", 102500007, nil, nil, nil, nil, nil, true, },
[102500008]={102500008, 2, 2, "战斗7", 102500008, nil, nil, nil, nil, nil, true, },
[102500009]={102500009, 2, 2, "战斗8_眺望点附近", 102500009, nil, nil, nil, nil, nil, true, },
[102500010]={102500010, 2, 2, "战斗9", 102500010, nil, nil, nil, nil, nil, true, },
[102500011]={102500011, 2, 2, "战斗10", 102500011, nil, nil, nil, nil, nil, true, },
[102500012]={102500012, 2, 2, "战斗11_boss", 102500012, nil, nil, nil, nil, nil, true, },
[102500013]={102500013, 2, 2, "支线战斗12", 102500013, nil, nil, nil, nil, nil, true, },
[102500014]={102500014, 2, 2, "支线战斗13", 102500014, nil, nil, nil, nil, nil, true, },
}
return config, 'ID', key