---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, WaveType=2, Enemy1=3, Enemy2=4, Enemy3=5, CameraCfgId=6, WaveCameraCfgId=7, OffsetPos1=8, OffsetPos2=9, OffsetPos3=10, OffsetForward1=11, OffsetForward2=12, OffsetForward3=13, TeamOffsetPos=14, TeamOffsetForward=15, }
local commonData = {{-4.799999, -0.31, 3.789993, }, {0.3400002, -0.31, 4.829994, }, {5.130001, -0.31, 3.149994, }, {0, 161.3101, 0, }, {0, 186.9112, 0, }, {0.26, 0, 2.94, }, {0, 180, 0, }, {0, 6.911188, 0, }, }
local config = {
[21]={21, 1, 100101, 100101, -1, 0, 0, commonData[1], commonData[2], commonData[3], commonData[4], commonData[5], commonData[5], commonData[6], commonData[7], },
[22]={22, 1, -1, -1, -1, 0, 0, commonData[1], commonData[2], commonData[3], commonData[4], commonData[5], commonData[5], {79.94273, 0.101841, -22.11957, }, commonData[7], },
[31]={31, 1, 100101, -1, -1, 0, 0, commonData[1], commonData[2], commonData[3], {0, 341.3101, 0, }, commonData[8], commonData[8], commonData[6], {0, 5.008956E-06, 0, }, },
[41]={41, 1, 100101, -1, -1, 0, 0, commonData[1], commonData[2], commonData[3], commonData[4], commonData[5], commonData[5], commonData[6], commonData[7], },
}
return config, 'ID', key