---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Res=2, MaxCount=3, StateMachineId=4, SurviceType=5, LifeTime=6, NormalSkill=7, BornBuffId=8, }
local config = {
{1, "fx_p_ghost_skill_03_freeze_start", 10, 4001, 1, 2000, 1003, },
{2, "fx_p_12000401_skill_03_land_loop", 1, 4002, 2, 40000, 10210603, 20016, },
}
return config, 'ID', key