---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ConfigName=1, Type=2, }
local config = {
["cfg_quest_type"]={"cfg_quest_type", 1, },
["cfg_quest_cond_type"]={"cfg_quest_cond_type", 2, },
["cfg_quest_cond"]={"cfg_quest_cond", 3, },
["cfg_quest_group"]={"cfg_quest_group", 5, },
["cfg_quest_test"]={"cfg_quest_test", 4, },
}
return config, 'ConfigName', key