---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, GroupName=2, DungeonID=3, QuestList=4, }
local config = {
[10001]={10001, "测试任务组10001", 10001, {10001, 10002, 10003, 10004, }, },
[20001]={20001, "测试任务组20001", 10002, {20001, 20002, }, },
}
return config, 'ID', key