---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, QuestType=2, QuestName=3, QuestDesc=4, PreCond=5, UnlockCond=6, plot1=7, AcceptCond=8, plot2=9, DeliveryCond=10, plot3=11, CompleteCond=12, plot4=13, QuestAward=14, AwardIcon=15, QuestJunp=16, QuestGroup=17, AfterId=18, Show=19, Controller=20, }
local commonData = {{100102004, }, {100101002, }, {{3, 100, 200, }, {5, 999, }, }, }
local config = {
[10001]={10001, 1, "测试任务10001", "任务组10001,任务完成解锁任务10002", nil, nil, nil, nil, nil, nil, nil, "10001", commonData[1], commonData[3], nil, nil, 10001, {10002, }, },
[10002]={10002, 1, "测试任务10002", "任务组10001,任务完成解锁任务10003", "10001", nil, nil, nil, nil, nil, nil, "10001", commonData[1], nil, nil, nil, 10001, {10003, }, },
[10003]={10003, 1, "测试任务10003", "任务组10001,任务完成解锁任务10004", "10002", nil, nil, nil, nil, nil, nil, "10001", commonData[1], nil, nil, nil, 10001, {10004, }, },
[10004]={10004, 1, "测试任务10004", "任务组10001,任务完成后没有后续任务", "10003", nil, nil, nil, nil, nil, nil, "10001", commonData[1], nil, nil, nil, 10001, },
[10005]={10005, 1, "测试任务10005", "散任务10005,无后续任务", nil, nil, nil, nil, nil, nil, nil, "10005", nil, commonData[3], },
[20001]={20001, 2, "测试任务20001", "任务组20001,任务完成解锁任务20002", nil, nil, nil, nil, nil, nil, nil, "20001", commonData[2], nil, nil, nil, 20001, {20002, }, },
[20002]={20002, 2, "测试任务20002", "任务组20001,任务完成解锁任务20003", "20001", nil, nil, nil, nil, nil, nil, "20001", commonData[2], },
[20003]={20003, 2, "测试任务20003", "散任务20003,无后续任务", nil, nil, nil, nil, nil, nil, nil, "20003", },
}
return config, 'ID', key