---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, QuestType=2, QuestName=3, QuestDesc=4, PreCond=5, UnlockCond=6, plot1=7, AcceptCond=8, plot2=9, DeliveryCond=10, plot3=11, CompleteCond=12, plot4=13, QuestAward=14, AwardIcon=15, QuestJunp=16, QuestGroup=17, AfterId=18, Show=19, Controller=20, }
local config = {
{1, 1, "和耐鲁交谈", "完成条件：完成耐鲁对话剧情（完成后应该会再播一遍剧情动画）", nil, nil, nil, nil, nil, nil, nil, "1", {100102004, }, nil, nil, nil, nil, {2, }, },
{2, 1, "进入异变区域", "完成条件：进入体验关（完成副本出生点事件）", "1", nil, nil, nil, nil, nil, nil, "2", nil, nil, nil, nil, 1001, {3, }, },
{3, 1, "异变根源", "完成条件：打败体验关的第一波怪", "2", nil, nil, nil, nil, nil, nil, "3", nil, nil, nil, nil, 1001, {4, }, },
{4, 1, "空中废墟", "完成条件：解锁第一个区域的小地图", "3", nil, nil, nil, nil, nil, nil, "4", nil, nil, nil, nil, 1001, },
[101]={101, 2, "寻找千世和祐希", "解锁条件：完成主线任务1。完成条件：完成千世祐希的剧情事件（完成后应该会再播一遍剧情动画）", "1", nil, nil, nil, nil, nil, nil, "101", {100101002, }, nil, nil, nil, nil, {102, }, },
[102]={102, 2, "通关挑战关", "解锁条件：完成三人剧情任务。完成条件：通关挑战关", "101", nil, nil, nil, nil, nil, nil, "102", },
}
return config, 'ID', key