---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Name=2, Cond=3, CondDesc=4, AutoAccept=5, AcceptCond=6, AcceptCondDesc=7, UnlockCond=8, UnlockCondDesc=9, PreID=10, Version=11, }
local config = {
[201]={201, "任务4", "type :1", "str_common_always_true", true, "type :2", nil, "type :3", nil, "id:3", 0, },
[202]={202, "任务5", "type :3,target:1000", "str_common_quest_get_coin", nil, "type :2", nil, "type :3", nil, "id:3|id:4", 1, },
[203]={203, "任务6", "type :2,target:10", "str_common_always_true", true, "type :3", nil, "type :3", nil, "id:3&id:4", 1, },
[204]={204, "任务7", "type :2,target:10", "str_common_always_true", true, "type :2,target:5", nil, "type :2,target:0", },
}
return config, 'ID', key