---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Name=2, Cond=3, CondDesc=4, AutoAccept=5, AcceptCond=6, AcceptCondDesc=7, }
local config = {
{1, "任务1", "type:1", "str_common_always_true", true, },
{2, "任务2", "type :3,target:1000", "str_common_quest_get_coin", },
}
return config, 'ID', key