---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Name=2, UnlockCond=3, QuestDesc=4, OneTimeQuest=5, RefreshPeriod=6, RefreshTime=7, RefreshWay=8, Random=9, RandomQuestPool=10, RandomRefreshNumber=11, RandomAcceptNumber=12, AbandonReset=13, }
local config = {
{1, "主线任务", {1, }, },
{2, "支线任务", {1, 2, }, },
{3, "角色任务", {1, 2, 3, }, },
}
return config, 'ID', key