---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, CondCopy=2, CondType=3, Cond1=4, Cond2=5, Cond3=6, Cond4=7, Controller=8, }
local config = {
{1, "和耐鲁对话", "1", "type:11,param_1:30001,param_2:300010013", },
{2, "进入副本", "1", "type:11,param_1:10201,param_2:100010", },
{3, "击败怪物", "1", "type:11,param_1:10201,param_2:100200", },
{4, "解锁小地图", "1", "type:11,param_1:10201,param_2:100420", },
[101]={101, "和祐希对话", "1", "type:11,param_1:30001,param_2:300010014", },
[102]={102, "通关副本", "1", "type:12,param_1:10202", },
[10001]={10001, "测试任务条件10001", "1", "type:3,param_1:1", },
[10005]={10005, "完成任务10004", "1", "type:5,param_1:10004", },
[20001]={20001, "测试任务条件20001", "1", "type:3,param_1:1", },
[20003]={20003, "完成任务20002", "1", "type:5,param_1:20002", },
}
return config, 'ID', key