---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, EventType=2, EventTriggerType=3, Des=4, CorrelationIDs=5, EventTriggerConditionGroupID=6, EventActiveConditionGroupID=7, MapElementID=8, EventReward=9, MapAreaID=10, ForcedShow=11, }
local config = {
[100010]={100010, 1, 1, "出生点", 0, },
[100020]={100020, 5, 1, "胜利点", 0, },
}
return config, 'ID', key