---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, WaveType=2, Enemy1=3, Enemy2=4, Enemy3=5, CameraCfgId=6, WaveCameraCfgId=7, OffsetPos1=8, OffsetPos2=9, OffsetPos3=10, OffsetEulerAngles1=11, OffsetEulerAngles2=12, OffsetEulerAngles3=13, TeamOffsetPos=14, TeamOffEulerAngles=15, WaveBuffList=16, }
local commonData = {{4.8, 0, 3.79, }, {0.62, 0, 4.47, }, {-5.13, 0, 3.15, }, {0, 180, 0, }, {0, 0, 4, }, }
local config = {
[1031]={1031, 1, 100126, 100127, 100126, 8, 1, commonData[1], commonData[2], commonData[3], commonData[4], commonData[4], commonData[4], commonData[5], commonData[4], },
[1032]={1032, 1, 100126, 100127, 100126, 8, 1, commonData[1], commonData[2], commonData[3], commonData[4], commonData[4], commonData[4], commonData[5], commonData[4], },
}
return config, 'ID', key