---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, WaveType=2, Enemy1=3, Enemy2=4, Enemy3=5, CameraCfgId=6, WaveCameraCfgId=7, OffsetPos1=8, OffsetPos2=9, OffsetPos3=10, OffsetEulerAngles1=11, OffsetEulerAngles2=12, OffsetEulerAngles3=13, TeamOffsetPos=14, TeamOffsetEulerAngles=15, WaveBuffList=16, }
local commonData = {{-3.400002, 0, 1.699997, }, {-0.5, 0, 3.5, }, {2.299999, 0, 2.099998, }, {0, 180, 0, }, {0, 0, 4.3, }, }
local config = {
[10000]={10000, 1, -1, 100101, -1, 0, 0, commonData[1], commonData[2], commonData[3], commonData[4], commonData[4], commonData[4], commonData[5], commonData[4], },
[10001]={10001, 1, -1, 100107, -1, 0, 0, commonData[1], commonData[2], commonData[3], commonData[4], commonData[4], commonData[4], commonData[5], commonData[4], },
[10002]={10002, 1, -1, 100102, -1, 0, 0, commonData[1], commonData[2], commonData[3], commonData[4], commonData[4], commonData[4], commonData[5], commonData[4], },
[10003]={10003, 1, -1, 100111, -1, 0, 0, commonData[1], commonData[2], commonData[3], commonData[4], commonData[4], commonData[4], commonData[5], commonData[4], },
[10004]={10004, 1, -1, 100111, -1, 0, 0, commonData[1], commonData[2], commonData[3], commonData[4], commonData[4], commonData[4], commonData[5], commonData[4], },
[10005]={10005, 1, -1, 100111, -1, 0, 0, commonData[1], commonData[2], commonData[3], commonData[4], commonData[4], commonData[4], commonData[5], commonData[4], },
[10006]={10006, 1, -1, 100101, -1, 0, 0, commonData[1], commonData[2], commonData[3], commonData[4], commonData[4], commonData[4], commonData[5], commonData[4], },
[10007]={10007, 1, -1, 100102, -1, 0, 0, commonData[1], commonData[2], commonData[3], commonData[4], commonData[4], commonData[4], commonData[5], commonData[4], },
[10008]={10008, 1, -1, 100107, -1, 0, 0, commonData[1], commonData[2], commonData[3], commonData[4], commonData[4], commonData[4], commonData[5], commonData[4], },
[10009]={10009, 1, -1, 100102, -1, 0, 0, commonData[1], commonData[2], commonData[3], commonData[4], commonData[4], commonData[4], commonData[5], commonData[4], },
[10010]={10010, 1, -1, 100112, -1, 0, 0, commonData[1], commonData[2], commonData[3], commonData[4], commonData[4], commonData[4], commonData[5], commonData[4], },
[10011]={10011, 1, -1, 100102, -1, 0, 0, commonData[1], commonData[2], commonData[3], commonData[4], commonData[4], commonData[4], commonData[5], commonData[4], },
[10012]={10012, 1, -1, 100102, -1, 0, 0, commonData[1], commonData[2], commonData[3], commonData[4], commonData[4], commonData[4], commonData[5], commonData[4], },
}
return config, 'ID', key