---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, EventType=2, EventTriggerType=3, Des=4, CorrelationIDs=5, EventTriggerConditionGroupID=6, EventActiveConditionGroupID=7, EventReward=8, }
local config = {
[100010]={100010, 1, 1, "角色出生点", 0, },
[100020]={100020, 2, 2, "战斗1-待机怪物", 10012, },
[100030]={100030, 2, 2, "战斗2-随机出生", 10013, },
[100040]={100040, 2, 2, "战斗3-巡逻", 10014, },
}
return config, 'ID', key