---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ProductID=1, Name=2, TimeUnit=3, Length=4, Price=5, ServiceCode=6, RenewRemind=7, RewardList=8, }
local commonData = {{{21020401,1,}, }, }
local config = {
["com.tencent.baiye.testcard1.7"]={"com.tencent.baiye.testcard1.7", "测试月卡1", "day", 7, 100, "testcard1", 1, commonData[1], },
["com.tencent.baiye.testcard1.30"]={"com.tencent.baiye.testcard1.30", "测试月卡2", "day", 30, 200, "testcard1", 1, commonData[1], },
["com.tencent.baiye.testcard2.30"]={"com.tencent.baiye.testcard2.30", "测试月卡3", "day", 30, 100, "testcard2", 1, {{21020501,2,}, }, },
["com.tencent.baiyeint.testcard1.7"]={"com.tencent.baiyeint.testcard1.7", "测试月卡1", "day", 7, 100, "testcard1", 1, commonData[1], },
["com.tencent.baiyeint.testcard1.15"]={"com.tencent.baiyeint.testcard1.15", "测试月卡一15D", "day", 15, 150, "testcard1", 1, commonData[1], },
["com.tencent.baiyeint.testcard1.30"]={"com.tencent.baiyeint.testcard1.30", "测试月卡2", "day", 30, 200, "testcard1", 1, commonData[1], },
}
return config, 'ProductID', key