---this config file was auto-generated by Excel2lua tool, do not modify it!

local config = {
["str_ui_city_map_area"]="AREA", ["str_ui_city_map_decorate_txt2_unlock_fight"]="DNAGER AREA", ["str_ui_city_map_decorate_txt3_unlock_life"]="NORMAL AREA", }
return config