---this config file was auto-generated by Excel2lua tool, do not modify it!

local config = {
["str_ui_team_pre_team1"]="チーム1", ["str_ui_team_support_name"]="サポート役割", ["str_ui_team_btn_fastFormation"]="すばやく", ["str_ui_team_btn_embattle"]="布陣する", ["str_ui_team_battle"]="と戦う", ["str_ui_team_embattle"]="チームを組む", }
return config