---this config file was auto-generated by Excel2lua tool, do not modify it!

local config = {
["str_ui_story_cancel"]="CANCEL", ["str_ui_story_skip"]="SKIP", ["str_ui_story_autoSign"]="AUTO", ["str_ui_story_skipSign"]="SKIP", ["str_ui_story_second"]="s", ["str_ui_story_Title"]="あらすじ", }
return config