---this config file was auto-generated by Excel2lua tool, do not modify it!

local config = {
["ui_pet_tag_friend_1"]="啓光連邦の将軍", ["ui_pet_tag_friend_2"]="支援本部", ["ui_pet_tag_friend_3"]="科学研究室", ["ui_pet_tag_friend_4"]="四大天使", ["ui_pet_tag_friend_5"]="アップタウン", ["ui_pet_tag_friend_6"]="法廷", ["ui_pet_tag_friend_7"]="学院聖歌隊", ["ui_pet_tag_friend_8"]="イスタバン", ["ui_pet_tag_friend_9"]="影ノ街の一匹狼", ["ui_pet_tag_friend_10"]="北境宮廷", ["ui_pet_tag_friend_11"]="ウーヌス", ["ui_pet_tag_friend_12"]="決死隊", ["ui_pet_tag_friend_13"]="R·W音楽祭", ["ui_pet_tag_friend_14"]="カナリアとキジバト", ["ui_pet_tag_friend_15"]="クーリエギルド", ["ui_pet_tag_friend_16"]="暗鬼スレーブ", ["ui_pet_tag_friend_17"]="光霊スレイヤー", ["ui_pet_tag_friend_18"]="暗鬼の異端者", ["ui_pet_tag_friend_19"]="日蝕の従者", }
return config