---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, BattleType=2, WaveList=3, BattleEnterTL=4, }
local config = {
[10011]={10011, 1, {100111, 100112, }, },
}
return config, 'ID', key