---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, WaveType=2, Enemy1=3, Enemy2=4, Enemy3=5, CameraCfgId=6, WaveCameraCfgId=7, OffsetPos1=8, OffsetPos2=9, OffsetPos3=10, OffsetForward1=11, OffsetForward2=12, OffsetForward3=13, TeamOffsetPos=14, TeamOffsetForward=15, }
local commonData = {{4.8, 0, -3.79, }, {0.62, 0, -4.47, }, {-5.13, 0, -3.15, }, {0, 0, 0, }, {0, 0, -4, }, }
local config = {
[100111]={100111, 1, nil, 100103, nil, 5, 1, commonData[1], commonData[2], commonData[3], commonData[4], commonData[4], commonData[4], commonData[5], commonData[4], },
[100112]={100112, 1, nil, 100103, nil, 5, 1, commonData[1], commonData[2], commonData[3], commonData[4], commonData[4], commonData[4], commonData[5], commonData[4], },
}
return config, 'ID', key