---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, BattleType=2, WaveList=3, BattleEnterTL=4, EnterPos1=5, EnterPos2=6, ShowMonsterInfo=7, }
local config = {
[101]={101, 1, {1011, }, nil, nil, nil, {1, }, },
}
return config, 'ID', key