---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Type=2, InitSkin=3, WeaponType=4, Health=5, ATK=6, RDM=7, CRT=8, CRTD=9, ActionSkills=10, PassiveSkills=11, UniqueSkills=12, EffectScale=13, ZoomCamaraMaxHeigh=14, ZoomCamaraMinHeigh=15, InitLinks=16, Behit1AnimaInterval=17, Behit2AnimaInterval=18, Story=19, }
local commonData = {{0, }, }
local config = {
[100000001]={100000001, 0, {110010001, }, 0, 0, 0, 0, 0, 0, commonData[1], commonData[1], commonData[1], 1, 0, 0, },
}
return config, 'ID', key