---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Type=2, Level=3, CharID=4, }
local config = {
[120300001]={120300001, 3, 1, },
}
return config, 'ID', key