---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Name=2, icon=3, Rank=4, ItemType=5, ItemSubType=6, BagType=7, BagIndex=8, Overlay=9, CanUse=10, param1=11, param2=12, param3=13, param4=14, param5=15, Intro=16, RpIntro=17, Soldprice=18, UseType=19, }
local config = {
[21020101]={21020101, "小经验瓶", "21020101_icon", 1, 1, 2, 1, 800, 9999, 2, 1000, 0, 0, 0, 0, "使用可获得1000点卡牌经验。", "从紫竹林中萃取的精华，饮用后会有神奇的效果。", 0, 3, },
[21020201]={21020201, "大经验瓶", "21020101_icon", 2, 1, 2, 1, 800, 9999, 2, 1000, 0, 0, 0, 0, "使用可获得3000点卡牌经验。", "从紫竹林中萃取的精华，饮用后会有神奇的效果。", 0, 3, },
[21020301]={21020301, "超大经验瓶", "21020101_icon", 3, 1, 2, 1, 800, 9999, 2, 1001, 0, 0, 0, 0, "使用可获得10000点卡牌经验。", "从紫竹林中萃取的精华，饮用后会有神奇的效果。", 0, 3, },
}
return config, 'ID', key