---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, SubType=2, TLimitType=3, LevelLimit=4, SenceLimit=5, UseTimes=6, Timelimit=7, Rewards=8, Othercondition=9, }
local config = {
["21020401"]={"21020401", 1, 0, 0, false, 1, nil, "1,500|2,200", },
["21020501"]={"21020501", 1, 1, 2, true, 2, "2021-12-20", "1,1000|3,200", },
["21020601"]={"21020601", 1, 2, 4, true, 4, "17:00,22:00", "1,50|2,500", },
}
return config, 'ID', key