---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Name=2, icon=3, Rank=4, ItemType=5, ItemSubType=6, BagType=7, BagIndex=8, Overlay=9, CanUse=10, AddGoldAmount=11, Intro=12, RpIntro=13, Soldprice=14, UseType=15, }
local config = {
[22000001]={22000001, "小金条", "21020101_icon", 1, 2, 2, 1, 800, 9999, 2, 100, "使用可获得100金币", "从紫竹林中萃取的精华，饮用后会有神奇的效果。", 0, 3, },
[22000002]={22000002, "大金条", "21020101_icon", 1, 2, 2, 1, 800, 9999, 2, 1000, "使用可获得1000金币", "从紫竹林中萃取的精华，饮用后会有神奇的效果。", 0, 3, },
[22000003]={22000003, "金币", "21020101_icon", 1, 2, 2, 1, 800, 9999, 2, 10000, "使用可获得10000金币", "从紫竹林中萃取的精华，饮用后会有神奇的效果。", 0, 3, },
}
return config, 'ID', key