---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, WaveType=2, Enemy1=3, Enemy2=4, Enemy3=5, ExtraEnemy=6, CameraCfgId=7, WaveCameraCfgId=8, OffsetPos1=9, OffsetPos2=10, OffsetPos3=11, OffsetEulerAngles1=12, OffsetEulerAngles2=13, OffsetEulerAngles3=14, TeamOffsetPos=15, TeamOffsetEulerAngles=16, WaveBuffList=17, }
local commonData = {{-0.5000216, 0, 3.499998, }, {0, 180, 0, }, {-3.4, 0, 1.7, }, {-0.5, 0, 3.5, }, {1.761907, 0, 1.921657, }, {0, 0, 4.3, }, {2.3, 0, 2.1, }, {-3.400002, 0, 1.699997, }, {2.299999, 0, 2.099998, }, {"20000002|1", }, }
local config = {
[41]={41, 1, -1, 200101, -1, nil, 1, 0, {-3.400023, 0, 1.699982, }, commonData[1], {2.299991, 0, 2.100013, }, commonData[2], commonData[2], commonData[2], {-2.81781E-05, 0, 4.300002, }, commonData[2], commonData[10], },
[61]={61, 1, 200501, -1, 200502, nil, 1, 0, commonData[3], commonData[4], commonData[5], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], commonData[10], },
[71]={71, 1, -1, 200401, -1, nil, 1, 0, commonData[3], commonData[4], commonData[7], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], commonData[10], },
[81]={81, 1, -1, 200701, -1, nil, 2, 0, {-3.400009, 0, 1.699982, }, {-0.5000153, 0, 3.499997, }, {2.299988, 0, 2.100013, }, commonData[2], commonData[2], commonData[2], {-3.051758E-05, 0, 4.3, }, commonData[2], commonData[10], },
[91]={91, 1, 200804, 200801, 200805, nil, 1, 0, commonData[3], commonData[4], commonData[7], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], commonData[10], },
[92]={92, 1, 200801, 200802, 200801, nil, 1, 0, commonData[3], commonData[4], commonData[7], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], },
[101]={101, 1, -1, 200901, -1, nil, 1, 0, commonData[3], commonData[4], commonData[7], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], commonData[10], },
[111]={111, 1, 201001, -1, 201001, nil, 1, 0, commonData[3], commonData[4], commonData[5], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], commonData[10], },
[121]={121, 1, 201101, 201102, 201103, nil, 1, 0, commonData[3], commonData[4], commonData[7], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], commonData[10], },
[131]={131, 1, 200301, -1, 200301, nil, 1, 0, commonData[3], commonData[4], commonData[7], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], commonData[10], },
[141]={141, 1, -1, 200601, -1, nil, 1, 0, commonData[3], commonData[4], commonData[7], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], commonData[10], },
[151]={151, 1, 201201, -1, 201202, nil, 1, 0, {-3.40001, 0.2291489, 1.699981, }, {-0.5000216, 0, 3.499999, }, commonData[5], commonData[2], commonData[2], commonData[2], {-2.365559E-05, 7.629395E-06, 4.3, }, commonData[2], commonData[10], },
[161]={161, 1, 201301, -1, 201301, nil, 1, 0, commonData[3], commonData[4], commonData[7], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], commonData[10], },
[171]={171, 1, 201401, 201402, 201403, nil, 1, 0, commonData[3], commonData[4], commonData[7], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], commonData[10], },
[181]={181, 1, -1, 201501, -1, nil, 1, 0, commonData[3], commonData[4], commonData[7], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], commonData[10], },
[191]={191, 1, 201502, 201501, 201503, nil, 1, 0, commonData[3], commonData[4], commonData[7], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], commonData[10], },
[201]={201, 1, 201701, 201702, 201703, nil, 1, 0, commonData[3], commonData[4], commonData[7], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], commonData[10], },
[211]={211, 1, 201801, -1, 201802, nil, 1, 0, commonData[3], commonData[4], commonData[5], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], commonData[10], },
[221]={221, 1, 200102, -1, -1, nil, 1, 0, commonData[3], commonData[4], commonData[7], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], commonData[10], },
[231]={231, 1, -1, 201901, -1, nil, 3, 0, {-3.400023, 0, 1.69998, }, commonData[1], {2.299991, 0, 2.100011, }, commonData[2], commonData[2], commonData[2], {-2.812967E-05, -13.75, 4.300009, }, commonData[2], commonData[10], },
[241]={241, 1, 202001, 202001, 202001, nil, 1, 0, commonData[3], commonData[4], commonData[7], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], commonData[10], },
[242]={242, 1, 202001, 202002, 202001, nil, 1, 0, commonData[3], commonData[4], commonData[7], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], },
[1008001]={1008001, 1, 203002, 202002, 203003, nil, 1, 0, commonData[8], commonData[4], commonData[9], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], commonData[10], },
[1008002]={1008002, 1, 203002, 203001, 203003, nil, 1, 0, commonData[8], commonData[4], commonData[9], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], },
[1008101]={1008101, 1, 203002, 202002, 203003, nil, 1, 0, commonData[8], commonData[4], commonData[9], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], commonData[10], },
[1008102]={1008102, 1, -1, 200401, -1, nil, 1, 0, commonData[8], commonData[4], commonData[9], commonData[2], commonData[2], commonData[2], commonData[6], commonData[2], },
[10000]={10000, 1, 200202, -1, 200202, nil, 0, 0, {-3.400002, -9.536743E-07, 1.699996, }, {-0.5000005, 0, 3.5, }, commonData[5], commonData[2], commonData[2], commonData[2], {-4.768372E-07, 0, 4.300004, }, commonData[2], commonData[10], },
}
return config, 'ID', key