---this config file was auto-generated by Excel2lua tool, do not modify it!

local config = {
["str_ui_team_pre_team1"]="Team1", ["str_ui_team_pre_team2"]="Team2", ["str_ui_team_pre_team3"]="Team3", ["str_ui_team_btn_fastFormation"]="quick", ["str_ui_team_btn_enterdunage"]="Enter copy", ["str_ui_team_lv_sort"]="Rankorder", ["str_ui_team_no_selecthero"]="No_selected_role", }
return config