---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, EventType=2, EventTriggerType=3, Des=4, CorrelationIDs=5, EventTriggerConditionGroupID=6, EventActiveConditionGroupID=7, EventCompleteConditionGroupID=8, MapElementID=9, EventReward=10, ForcedShow=11, }
local config = {
[121310000]={121310000, 2, 1, "daw", 121310000, nil, nil, nil, nil, nil, false, },
[121310001]={121310001, 2, 1, "daw", 121310001, nil, nil, nil, nil, nil, false, },
[121310002]={121310002, 2, 1, "daw", 121310002, nil, nil, nil, nil, nil, false, },
}
return config, 'ID', key