---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, WaveType=2, Enemy1=3, Enemy2=4, Enemy3=5, CameraCfgId=6, WaveCameraCfgId=7, OffsetPos1=8, OffsetPos2=9, OffsetPos3=10, OffsetEulerAngles1=11, OffsetEulerAngles2=12, OffsetEulerAngles3=13, TeamOffsetPos=14, TeamOffsetEulerAngles=15, WaveBuffList=16, }
local commonData = {{0, 180, 0, }, }
local config = {
[10000]={10000, 1, -1, 100103, -1, 0, 0, {-3.400002, 0, 1.699997, }, {-0.5, 0, 3.5, }, {2.299999, 0, 2.099998, }, commonData[1], commonData[1], commonData[1], {0, 0, 4.3, }, commonData[1], },
}
return config, 'ID', key