---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, BattleType=2, WaveList=3, BattleEnterTL=4, EnterPos1=5, EnterPos2=6, DeathTimeline=7, }
local config = {
[124440001]={124440001, 1, {10000, }, nil, {-6.277319, 0, -11.07948, }, {3.183969, 0, -11.50642, }, },
}
return config, 'ID', key