---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, value=2, }
local config = {
{1, "08|30", },
{2, "10|0", },
{3, "17|20", },
{4, "19|34", },
}
return config, 'ID', key