---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {Id=1, PitchAngle=2, ThrowSpeed=3, ThrowGravity=4, ThrowCameraFov=5, ThrowCameraDis=6, ThrowCameraOffsetRight=7, AttractRange=8, AttractHigh=9, AttractTimeMS=10, EnterThrowTimeMS=11, BallRes=12, LineResGreenOut=13, LineResGreenRange=14, LineResRedOut=15, LineResRedRange=16, }
local config = {
{1, 30, 8.5, 9.8, 50, 1.8, 0.6, 3, 3, 5000, 500, "ThrowBall", "fx_p_ui_throwroute_green", "fx_p_ui_throwrange_green", "fx_p_ui_throwroute_red", "fx_p_ui_throwrange_red", },
}
return config, 'Id', key