---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, AnimName=2, EffectBuffs=3, BuffToasts=4, }
local config = {
{1, nil, {20000001, }, {"str_ui_battle_buff_tips_98", }, },
}
return config, 'ID', key