---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, BattleType=2, WaveList=3, BattleEnterTL=4, EnterPos1=5, EnterPos2=6, DeathTimeline=7, }
local commonData = {{-6.277319, 0, -11.07948, }, {3.183969, 0, -11.50642, }, {0, 0, 0, }, }
local config = {
[121310000]={121310000, 1, {10000, }, nil, commonData[1], commonData[2], },
[121310001]={121310001, 1, {10001, }, nil, commonData[1], commonData[2], },
[121310002]={121310002, 1, {10002, }, nil, commonData[3], commonData[3], },
}
return config, 'ID', key