---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, BattleType=2, WaveList=3, BattleEnterTL=4, EnterPos1=5, EnterPos2=6, DeathTimeline=7, }
local commonData = {{0, 0, 0, }, }
local config = {
[102020022]={102020022, 1, {10015, }, nil, commonData[1], commonData[1], },
[102020021]={102020021, 1, {10014, 100141, }, nil, commonData[1], commonData[1], },
[102020020]={102020020, 1, {10013, }, nil, commonData[1], commonData[1], },
[102020019]={102020019, 1, {10012, }, nil, commonData[1], commonData[1], },
[102020018]={102020018, 1, {10011, }, nil, commonData[1], commonData[1], },
[102020013]={102020013, 1, {10006, }, nil, commonData[1], commonData[1], },
[102020014]={102020014, 1, {10007, }, nil, commonData[1], commonData[1], },
[102020015]={102020015, 1, {10008, }, nil, commonData[1], commonData[1], },
[102020016]={102020016, 1, {10009, }, nil, commonData[1], commonData[1], },
[102020017]={102020017, 1, {10010, }, nil, commonData[1], commonData[1], },
[102020023]={102020023, 1, {10016, 100161, }, nil, commonData[1], commonData[1], },
[102020025]={102020025, 1, {10017, }, nil, commonData[1], commonData[1], },
[102020026]={102020026, 1, {10018, }, nil, commonData[1], commonData[1], },
[102020027]={102020027, 1, {10019, }, nil, commonData[1], commonData[1], },
[102020028]={102020028, 1, {10020, }, nil, commonData[1], commonData[1], },
[102020029]={102020029, 1, {10021, }, nil, commonData[1], commonData[1], },
[102020030]={102020030, 1, {10022, }, nil, commonData[1], commonData[1], },
[102020032]={102020032, 1, {10023, }, nil, commonData[1], commonData[1], },
[102020033]={102020033, 1, {10024, }, nil, commonData[1], commonData[1], },
[102020034]={102020034, 1, {10025, }, nil, commonData[1], commonData[1], },
[102020035]={102020035, 1, {10026, }, nil, commonData[1], commonData[1], },
[102020036]={102020036, 1, {10027, }, nil, commonData[1], commonData[1], },
[102020037]={102020037, 1, {10028, 100281, }, nil, commonData[1], commonData[1], },
[102020039]={102020039, 1, {10029, 10030, }, nil, commonData[1], commonData[1], },
[102020040]={102020040, 1, {10031, 10032, }, nil, commonData[1], commonData[1], },
[102020041]={102020041, 1, {10033, 10034, }, nil, commonData[1], commonData[1], },
[102020042]={102020042, 1, {10035, 10036, }, nil, commonData[1], commonData[1], },
[102020043]={102020043, 1, {10037, 10038, }, nil, commonData[1], commonData[1], },
[102020044]={102020044, 1, {10039, 10040, 10041, }, nil, commonData[1], commonData[1], },
[102020076]={102020076, 1, {10042, }, nil, commonData[1], commonData[1], },
}
return config, 'ID', key