---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Conditions=2, }
local config = {
{1, "10601", },
{2, "10602", },
{3, "10603", },
}
return config, 'ID', key