---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Element=2, CalculateType=3, RangeType=4, OriginalType=5, ExtraType=6, }
local config = {
{1, nil, nil, nil, {1, 2, }, },
}
return config, 'ID', key