---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, ValueType=2, Value=3, }
local config = {
["CellHeight"]={"CellHeight", "float", "4", },
["AirFlyGravityAcceleration"]={"AirFlyGravityAcceleration", "float", "61", },
["AirDownGravityAcceleration"]={"AirDownGravityAcceleration", "float", "4", },
["ActorLandTime"]={"ActorLandTime", "float", "1", },
["ActionPointMaxCount"]={"ActionPointMaxCount", "float", "12", },
["ActionMaxProcess"]={"ActionMaxProcess", "float", "100", },
["ActionPointAddSpeedOnFree"]={"ActionPointAddSpeedOnFree", "float", "110", },
["ActionPointAddSpeedOnPlayerRound"]={"ActionPointAddSpeedOnPlayerRound", "float", "0", },
["ActionPointAddSpeedOnMonsterRound"]={"ActionPointAddSpeedOnMonsterRound", "float", "110", },
["ElementRestraintAtkPercent"]={"ElementRestraintAtkPercent", "float", "5000", },
["ElementRestraintGetEnergyPercent"]={"ElementRestraintGetEnergyPercent", "float", "5000", },
["BeElementRestraintAtkPercent"]={"BeElementRestraintAtkPercent", "float", "5000", },
["BeElementRestraintGetEnergyPercent"]={"BeElementRestraintGetEnergyPercent", "float", "5000", },
["ElementLinkTime"]={"ElementLinkTime", "float", "500", },
["ElementLinkEnforceTime"]={"ElementLinkEnforceTime", "float", "3000", },
["ElementLinkeTimeUseSkillDuration"]={"ElementLinkeTimeUseSkillDuration", "bool", "TRUE", },
["CustomCD"]={"CustomCD", "float", "500", },
["TeamSkillCD"]={"TeamSkillCD", "float", "0", },
["RoundEndWaitElementLink"]={"RoundEndWaitElementLink", "bool", "TRUE", },
["NormalKOTime"]={"NormalKOTime", "float", "20", },
["FirstFlyBulletTime"]={"FirstFlyBulletTime", "float", "500", },
["WaveAniTime"]={"WaveAniTime", "float", "2000", },
["EnergyBallRecoveredReduce"]={"EnergyBallRecoveredReduce", "float", "5000", },
["NextMonsterDelayTime"]={"NextMonsterDelayTime", "float", "0", },
}
return config, 'ID', key