---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {Id=1, PitchAngle=2, ThrowSpeed=3, ThrowGravity=4, ThrowCameraFov=5, ThrowCameraDis=6, ThrowCameraOffsetRight=7, AttractRange=8, AttractHigh=9, AttractTimeMS=10, EnterThrowTimeMS=11, }
local config = {
[30001]={30001, 30, 8.5, 9.8, 50, 1.8, 0.6, 3, 3, 5000, 500, },
}
return config, 'Id', key