---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, EventID=2, EventPos=3, TaskTitle=4, TaskContent=5, TaskPillar=6, TaskRout=7, IsShowDistance=8, }
local config = {
{1, 300010013, {29.5, 0.2, -37.5, }, "str_ui_city_temp_lifetask_title101", "str_ui_city_temp_lifetask_content101", false, false, true, },
{2, 300010014, {60.75, 0.45, -5.41, }, "str_ui_city_temp_lifetask_title102", "str_ui_city_temp_lifetask_content102", false, false, true, },
{3, 300010010, nil, "str_ui_city_temp_lifetask_title103", "str_ui_city_temp_lifetask_content103", false, false, false, },
}
return config, 'ID', key