---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, BehaviorType=2, BehaviorParam=3, }
local config = {
[10000]={10000, 2, },
[10001]={10001, 1, },
}
return config, 'ID', key