---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, EventType=2, EventTriggerType=3, Des=4, CorrelationIDs=5, EventTriggerConditionGroupID=6, EventActiveConditionGroupID=7, MapElementID=8, EventReward=9, ForcedShow=10, }
local commonData = {{1,30001001}, }
local config = {
[300010000]={300010000, 1, 1, "出生", 0, nil, nil, nil, nil, false, },
[300010010]={300010010, 12, 2, "NPC_耐鲁", 0, nil, nil, nil, nil, true, },
[300010011]={300010011, 12, 2, "NPC_千世", 0, commonData[1], commonData[1], nil, nil, true, },
[300010012]={300010012, 12, 2, "NPC_祐希", 0, commonData[1], commonData[1], nil, nil, true, },
[300010013]={300010013, 3, 2, "耐鲁双人剧情", 100101123, nil, nil, nil, nil, false, },
[300010014]={300010014, 3, 2, "千世祐希三人剧情", 100101999, commonData[1], commonData[1], nil, nil, false, },
}
return config, 'ID', key