---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, SourceConditionType=2, RelationalOperator=3, Param=4, }
local config = {
[30001001]={30001001, 10, 1, 300010013, },
}
return config, 'ID', key