---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {id=1, guide=2, sort=3, des=4, count=5, triggerlv=6, triggerDoneQuest=7, triggerRecQuest=8, triggerItem=9, funcOpen=10, triggerother=11, info=12, minlv=13, maxlv=14, showRules=15, continueGuide=16, canJump=17, }
local config = {
{1, 10, 1, "引导对局", nil, 5, nil, nil, nil, nil, nil, nil, 0, 30, },
{2, 20, nil, "引导牵绊选择特定id的角色", nil, 10, },
{3, 30, 2, "引导购买物品", 3, 15, },
{4, 40, nil, "引导使用物品", 3, nil, nil, nil, 21020401, nil, nil, nil, 0, 30, },
{5, 50, nil, "引导领取任务奖励", nil, nil, {1, }, },
}
return config, 'id', key