---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, triggers=2, test=3, }
local config = {
{1, 2, 1, },
{2, 2, 1, },
{3, 3, 1, },
{4, 1, 1, },
{5, 0, 1, },
}
return config, 'ID', key