---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, WaveType=2, Enemy1=3, Enemy2=4, Enemy3=5, CameraCfgId=6, WaveCameraCfgId=7, OffsetPos1=8, OffsetPos2=9, OffsetPos3=10, OffsetForward1=11, OffsetForward2=12, OffsetForward3=13, TeamOffsetPos=14, TeamOffsetForward=15, }
local commonData = {{0, 186.9112, 0, }, }
local config = {
[21]={21, 1, 100102, 100101, 100104, 0, 0, {-4.799999, -0.31, 3.789993, }, {0.3400002, -0.31, 4.829994, }, {5.130001, -0.31, 3.149994, }, {0, 161.3101, 0, }, commonData[1], commonData[1], {0.26, 0, 2.94, }, {0, 180, 0, }, },
}
return config, 'ID', key