---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, CameraBlendTime=2, CameraPauseTime=3, CameraTargetPos=4, CameraTargetEuler=5, CameraTargetFOV=6, }
local config = {
[10001]={10001, 1, 2, {58, 15.17, -56.76, }, {15, 35, 0, }, },
[10002]={10002, 2, 2, {34.98, 8.23, 49.84, }, {20, 210, 0, }, },
}
return config, 'ID', key