---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, EventID=2, EventPos=3, TaskTitle=4, TaskContent=5, TaskPillar=6, TaskRout=7, IsShowDistance=8, }
local config = {
{1, 100010, nil, nil, nil, nil, nil, true, },
{2, 100020, {159.59, 10, 17, }, "str_ui_city_temp_task_title101", "str_ui_city_temp_task_content101", true, true, true, },
{3, 100360, {162.2, 10, 4.2, }, "str_ui_city_temp_task_title101", "str_ui_city_temp_task_content101", true, true, true, },
{4, 100370, nil, "str_ui_city_temp_task_title101", "str_ui_city_temp_task_content102", nil, nil, true, },
{5, 100420, {127, 29, -42, }, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content103", nil, nil, true, },
{6, 100410, nil, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content105", nil, nil, true, },
{7, 100670, nil, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content105", nil, nil, true, },
{8, 100060, {61.5, 1.64, 12, }, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content105", nil, nil, true, },
{9, 100680, nil, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content106", nil, nil, true, },
{10, 100570, nil, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content106", nil, nil, true, },
{11, 100320, {29, 14.3, 2.1, }, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content107", nil, nil, true, },
{12, 100330, {15.7, 10.6, -43, }, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content107", nil, nil, true, },
{13, 100580, nil, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content108", nil, nil, true, },
{14, 100380, {-52.7, 1.5, -25, }, "str_ui_city_temp_task_title103", "str_ui_city_temp_task_content109", nil, nil, true, },
{15, 100390, {-62.4, 13.3, -27.2, }, "str_ui_city_temp_task_title103", "str_ui_city_temp_task_content110", nil, nil, true, },
{16, 100640, nil, "str_ui_city_temp_task_title103", "str_ui_city_temp_task_content111", nil, nil, true, },
{17, 100430, {-50, 57.3, -40, }, "str_ui_city_temp_task_title104", "str_ui_city_temp_task_content112", nil, nil, true, },
{18, 100700, nil, "str_ui_city_temp_task_title104", "str_ui_city_temp_task_content113", nil, nil, true, },
{19, 100710, nil, "str_ui_city_temp_task_title104", "str_ui_city_temp_task_content113", nil, nil, true, },
{20, 100590, nil, "str_ui_city_temp_task_title104", "str_ui_city_temp_task_content113", nil, nil, true, },
{21, 100600, nil, "str_ui_city_temp_task_title104", "str_ui_city_temp_task_content114", nil, nil, true, },
{22, 100610, nil, "str_ui_city_temp_task_title104", "str_ui_city_temp_task_content115", nil, nil, true, },
{23, 100620, nil, "str_ui_city_temp_task_title105", "str_ui_city_temp_task_content116", nil, nil, true, },
{24, 100540, nil, "str_ui_city_temp_task_title105", "str_ui_city_temp_task_content117", nil, nil, true, },
}
return config, 'ID', key