---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, AffectBehaviorType=2, AffectTargets=3, AffectBehaviorParam=4, }
local config = {
[21000001]={21000001, 1, {"23_231_201901", }, "-0.25", },
}
return config, 'ID', key