---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Des=2, RewardContent=3, }
local config = {
[100010]={100010, "体验关箱子", {{101,1}, {102,31}, {103,5}, }, },
}
return config, 'ID', key