---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, SourceConditionType=2, RelationalOperator=3, Param=4, }
local config = {
[10000]={10000, 10, 1, 124420001, },
[10010]={10010, 10, 1, 124420003, },
[10008]={10008, 10, 1, 124420007, },
[10009]={10009, 10, 1, 124420002, },
}
return config, 'ID', key