---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, EventType=2, EventTriggerType=3, Des=4, CorrelationIDs=5, EventTriggerConditionGroupID=6, EventActiveConditionGroupID=7, EventCompleteConditionGroupID=8, MapElementID=9, EventReward=10, ForcedShow=11, }
local config = {
[124420000]={124420000, 2, 1, "daw", 124420000, {2,10000,10008}, {1,10009}, {2,10010}, nil, nil, false, },
[124420001]={124420001, 2, 1, "daw", 124420001, nil, nil, nil, nil, nil, false, },
[124420002]={124420002, 2, 1, "daw", 124420002, nil, nil, nil, nil, nil, false, },
[124420003]={124420003, 2, 1, "daw", 124420003, nil, nil, nil, nil, nil, false, },
[124420004]={124420004, 2, 1, "wda", 124420004, nil, nil, nil, nil, nil, false, },
[124420005]={124420005, 2, 1, "daw", 124420005, nil, nil, nil, nil, nil, false, },
[124420006]={124420006, 1, 1, "wda", 0, nil, nil, nil, nil, nil, false, },
[124420007]={124420007, 2, 1, "daw", 124420007, nil, nil, nil, nil, nil, false, },
[124420008]={124420008, 2, 1, "daw", 124420008, nil, nil, nil, nil, nil, false, },
[124420009]={124420009, 2, 1, "da", 124420009, nil, nil, nil, nil, nil, false, },
[124420010]={124420010, 2, 1, "daw", 124420010, nil, nil, nil, nil, nil, false, },
[124420011]={124420011, 9, 1, "dawd", 124420011, nil, nil, nil, nil, nil, false, },
[124420012]={124420012, 4, 3, "dwa", 124420012, nil, nil, nil, nil, nil, false, },
[124420013]={124420013, 2, 1, "daw", 124420013, nil, nil, nil, nil, nil, false, },
[124420014]={124420014, 2, 1, "daw", 124420014, nil, nil, nil, nil, nil, false, },
}
return config, 'ID', key