---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, SourceConditionType=2, RelationalOperator=3, Param=4, }
local config = {
[10001]={10001, 10, 1, {100010, }, },
[10002]={10002, 10, 1, {100020, }, },
}
return config, 'ID', key