---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, EventType=2, EventTriggerType=3, Des=4, CorrelationIDs=5, EventTriggerConditionGroupID=6, EventActiveConditionGroupID=7, EventReward=8, MapElementID=9, }
local config = {
[100010]={100010, 1, 1, "出生点", nil, nil, nil, 300010, },
[100020]={100020, 2, 2, "战斗点", 10011, nil, {10001, }, 300010, },
[100030]={100030, 2, 2, "战斗点", 10011, nil, nil, 300020, },
[100040]={100040, 4, 3, "交互点", 1001, nil, nil, nil, 5001, },
[100050]={100050, 4, 3, "多阶段事件1", 1002, nil, nil, nil, 5001, },
[100060]={100060, 4, 3, "多阶段事件2", 1003, nil, nil, nil, 5001, },
[100070]={100070, 4, 3, "多阶段事件3", 1004, nil, nil, nil, 5001, },
[100080]={100080, 4, 3, "地图解锁点", 1005, nil, nil, nil, 7001, },
[100090]={100090, 4, 3, "交互大楼倒塌", 1006, nil, nil, nil, 7001, },
[100100]={100100, 8, 2, "自动平台", 100011, },
[100110]={100110, 9, 2, "特殊区域", 1, },
[100120]={100120, 10, 2, "多阶段", 100031, },
[100130]={100130, 3, 2, "剧情动画", 1001, },
[100140]={100140, 4, 3, "地图解锁点", 1005, nil, nil, nil, 7001, },
}
return config, 'ID', key