---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {filename=1, keyprefix=2, }
local config = {
["cfg_string_ui_chat"]={"cfg_string_ui_chat", {"str_ui_chat", }, },
["cfg_string_ui_common"]={"cfg_string_ui_common", {"str_common", }, },
["cfg_string_ui_login"]={"cfg_string_ui_login", {"str_ui_login", }, },
["cfg_enum2string"]={"cfg_enum2string", {"undefined", "sys_ret", "GET_DEFAULT_SERVER_CODE", "MOBILE_LOGIN_ERROR", "ROLE_RESULT_CODE", }, },
["cfg_string_demo"]={"cfg_string_demo", {"str_ui_demo", }, },
["cfg_string_ui_main"]={"cfg_string_ui_main", {"str_ui_main", }, },
["cfg_string_ui_battle"]={"cfg_string_ui_battle", {"str_ui_battle", }, },
["cfg_string_ui_city_map"]={"cfg_string_ui_city_map", {"str_ui_city_map", }, },
["cfg_string_ui_role_show"]={"cfg_string_ui_role_show", {"str_ui_role_show", }, },
["cfg_string_character"]={"cfg_string_character", {"str_character", "str_skin", }, },
["cfg_string_skill"]={"cfg_string_skill", {"string_skill", }, },
["cfg_string_ui_team"]={"cfg_string_ui_team", {"str_ui_team", }, },
["cfg_string_ui_city"]={"cfg_string_ui_city", {"str_ui_city", }, },
["cfg_string_guild"]={"cfg_string_guild", {"str_guild", }, },
["cfg_string_ui_story"]={"cfg_string_ui_story", {"str_ui_story", }, },
["cfg_string_monster"]={"cfg_string_monster", {"str_monster", }, },
["cfg_string_story_name_desc"]={"cfg_string_story_name_desc", {"str_story", }, },
["cfg_string_ui_tutorial"]={"cfg_string_ui_tutorial", {"str_tutorial", }, },
}
return config, 'filename', key