---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {filename=1, keyprefix=2, }
local config = {
["cfg_str_mainstory_ch999"]={"cfg_str_mainstory_ch999", {"str_mainstory_ch999", }, },
["cfg_str_mainstory_1_1_999"]={"cfg_str_mainstory_1_1_999", {"str_mainstory_1_1_999", }, },
["cfg_str_100101998"]={"cfg_str_100101998", {"str_100101998", }, },
["cfg_str_100101012"]={"cfg_str_100101012", {"str_100101012", }, },
["cfg_str_100102004"]={"cfg_str_100102004", {"str_100102004", }, },
["cfg_str_100101123"]={"cfg_str_100101123", {"str_100101123", }, },
["cfg_str_100101999"]={"cfg_str_100101999", {"str_100101999", }, },
["cfg_str_100101997"]={"cfg_str_100101997", {"str_100101997", }, },
["cfg_str_100101002"]={"cfg_str_100101002", {"str_100101002", }, },
["cfg_str_100101001"]={"cfg_str_100101001", {"str_100101001", }, },
["cfg_str_100101996"]={"cfg_str_100101996", {"str_100101996", }, },
["cfg_str_199901001"]={"cfg_str_199901001", {"str_199901001", }, },
["cfg_str_199901003"]={"cfg_str_199901003", {"str_199901003", }, },
["cfg_str_199901004"]={"cfg_str_199901004", {"str_199901004", }, },
["cfg_str_199901006"]={"cfg_str_199901006", {"str_199901006", }, },
}
return config, 'filename', key