---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, WaveType=2, Enemy1=3, Enemy2=4, Enemy3=5, CameraCfgId=6, WaveCameraCfgId=7, OffsetPos1=8, OffsetPos2=9, OffsetPos3=10, OffsetEulerAngles1=11, OffsetEulerAngles2=12, OffsetEulerAngles3=13, TeamOffsetPos=14, TeamOffEulerAngles=15, WaveBuffList=16, }
local commonData = {{0, 180, 0, }, }
local config = {
[1041]={1041, 1, nil, 100111, 100111, 8, 1, {-3.400017, 0, 1.699982, }, {-0.5000257, 0, 3.499997, }, {2.299995, 0, 2.100013, }, commonData[1], commonData[1], commonData[1], {-2.161786E-05, 0, 4.3, }, commonData[1], },
}
return config, 'ID', key