---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, PrefabName=2, EffectScale=3, Behit1AnimaInterval=4, Behit2AnimaInterval=5, HitNodes=6, WaveBornTl=7, DeathEffectTl=8, AirDeathEffectTl=9, BattleItemOffset=10, BattleItemScale=11, NormalDmgItemOffset=12, ThornDmgItemOffset=13, RecoverDmgItemOffset=14, }
local commonData = {{"Head", "Spine", "Waist", "Foot", }, {"-10|110", "100|130", "-80|105", "150|120", "-150|110", }, {"10|150", "-100|155", "160|160", "80|170", }, {"-10|110", "100|130", "-80|105", "160|120", "-160|110", }, {"-100|180", "160|165", "-190|170", "80|180", "-40|180", }, {"10|210", "-160|220", "190|215", "80|170", }, {0, 270, 0, }, {100, -180, 0, 180, }, {0, 240, 0, }, {80, -180, 0, 180, }, {0, 500, 0, }, {160, -200, 0, 200, }, {0, 900, 0, }, {-70, 486, 670, }, }
local config = {
[2700011]={2700011, "2700011", 1, 500, 500, commonData[1], "tl_0503_2700011_01", "tl_0501_2700011_01", "tl_0504_2700011_01", commonData[7], 1.2, commonData[8], commonData[2], commonData[3], },
[2700021]={2700021, "2700021", 1, 500, 500, commonData[1], "tl_0503_2700021_01", "tl_0501_2700021_01", "tl_0504_2700021_01", commonData[9], 1.2, commonData[10], commonData[2], commonData[3], },
[2700041]={2700041, "2700041", 1, 500, 500, commonData[1], "tl_0503_2700041_01", "tl_0501_2700041_01", "tl_0504_2700041_01", commonData[7], 1.2, commonData[8], commonData[2], commonData[3], },
[2700031]={2700031, "2700031", 1.5, 500, 500, nil, "tl_0503_2700031_01", "tl_0501_2700031_01", "tl_0504_2700031_01", commonData[11], 1.5, commonData[12], commonData[4], commonData[3], },
[2800051]={2800051, "2800051", 2, 500, 500, nil, nil, nil, nil, commonData[13], 2, commonData[12], commonData[5], commonData[6], },
[2800052]={2800052, "2800052", 2, 500, 500, nil, nil, nil, nil, commonData[13], 2, commonData[12], commonData[5], commonData[6], },
[2800061]={2800061, "2800061", 2, 500, 500, nil, "tl_0503_2800061_01", "tl_0501_2800061_01", nil, commonData[14], 2, commonData[12], commonData[5], commonData[6], },
[2710011]={2710011, "2700011", 1, 500, 500, commonData[1], "tl_0503_2700011_01", "tl_0501_2700011_01", "tl_0504_2700011_01", commonData[7], 1.2, commonData[8], commonData[2], commonData[3], },
[2710021]={2710021, "2700021", 1, 500, 500, commonData[1], "tl_0503_2700021_01", "tl_0501_2700021_01", "tl_0504_2700021_01", commonData[9], 1.2, commonData[10], commonData[2], commonData[3], },
[2710041]={2710041, "2700041", 1, 500, 500, commonData[1], "tl_0503_2700041_01", "tl_0501_2700041_01", "tl_0504_2700041_01", commonData[7], 1.2, commonData[8], commonData[2], commonData[3], },
[2710031]={2710031, "2700031", 1.5, 500, 500, nil, "tl_0503_2700031_01", "tl_0501_2700031_01", "tl_0504_2700031_01", commonData[11], 1.5, commonData[12], commonData[4], commonData[3], },
[2710032]={2710032, "2700031", 1.5, 500, 500, nil, "tl_0503_2700031_01", "tl_0501_2700031_01", "tl_0504_2700031_01", commonData[11], 1.5, commonData[12], commonData[4], commonData[3], },
[2710033]={2710033, "2700031", 1.5, 500, 500, nil, "tl_0503_2700031_01", "tl_0501_2700031_01", "tl_0504_2700031_01", commonData[11], 1.5, commonData[12], commonData[4], commonData[3], },
[2810051]={2810051, "2800051", 2, 500, 500, nil, nil, nil, nil, commonData[13], 2, commonData[12], commonData[5], commonData[6], },
[2810061]={2810061, "2800061", 2, 500, 500, nil, "tl_0503_2800061_01", "tl_0501_2800061_01", nil, commonData[14], 2, commonData[12], commonData[5], commonData[6], },
[2810062]={2810062, "2800061", 2, 500, 500, nil, "tl_0503_2800061_01", "tl_0501_2800061_01", nil, commonData[14], 2, commonData[12], commonData[5], commonData[6], },
[2720041]={2720041, "2700041", 1, 500, 500, commonData[1], "tl_0503_2700041_01", "tl_0501_2700041_01", "tl_0504_2700041_01", commonData[7], 1.2, commonData[8], commonData[2], commonData[3], },
[2820062]={2820062, "2800061", 2, 500, 500, nil, "tl_0503_2800061_01", "tl_0501_2800061_01", nil, commonData[14], 2, commonData[12], commonData[5], commonData[6], },
[2730011]={2730011, "2700021", 1, 500, 500, commonData[1], "tl_0503_2700021_01", "tl_0501_2700021_01", "tl_0504_2700021_01", commonData[9], 1.2, commonData[10], commonData[2], commonData[3], },
[2730021]={2730021, "2700031", 1.5, 500, 500, nil, "tl_0503_2700031_01", "tl_0501_2700031_01", "tl_0504_2700031_01", commonData[11], 1.5, commonData[12], commonData[4], commonData[3], },
[2730031]={2730031, "2700011", 1, 500, 500, commonData[1], "tl_0503_2700011_01", "tl_0501_2700011_01", "tl_0504_2700011_01", commonData[7], 1.2, commonData[8], commonData[2], commonData[3], },
[2730041]={2730041, "2700031", 1.5, 500, 500, nil, "tl_0503_2700031_01", "tl_0501_2700031_01", "tl_0504_2700031_01", commonData[11], 1.5, commonData[12], commonData[4], commonData[3], },
[2730051]={2730051, "2700041", 1, 500, 500, commonData[1], "tl_0503_2700041_01", "tl_0501_2700041_01", "tl_0504_2700041_01", commonData[7], 1.2, commonData[8], commonData[2], commonData[3], },
[2730061]={2730061, "2700041", 1, 500, 500, commonData[1], "tl_0503_2700041_01", "tl_0501_2700041_01", "tl_0504_2700041_01", commonData[7], 1.2, commonData[8], commonData[2], commonData[3], },
}
return config, 'ID', key