---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, StandHigh=2, LightJumpTime=3, HeavyJumpTime=4, ActorTurnAngleTime=5, WalkSpeed=6, RunSpeed=7, WalkAccel=8, WalkDecel=9, RunAccel=10, RunDecel=11, JumpHigh=12, JumpStopHigh=13, JumpTime=14, SquatHigh=15, SneakSpeed=16, SneakAccel=17, SneakDecel=18, ClimbSpeed=19, ClimbAccel=20, ClimbDecel=21, ClimbJumpDis=22, BlindageSpeed=23, BlindageAccel=24, BlindageDecel=25, FailCliffSpeed=26, CheckFallTimeMs=27, InitiativeAttackCfgID=28, }
local config = {
[0]={0, 1.7, 5, 1334, 0.01, 0.8, 6, 99999, 99999, 99999, 99999, 1.2, 10, 300, 1.2, 3, 99999, 99999, 4, 99999, 99999, 1, 3, 99999, 99999, 16, 250, 1, },
}
return config, 'ID', key