---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, AssetID=2, Sort=3, EliteLevel=4, Name=5, Des=6, Icon=7, ModelShowPos=8, ModelShowAni=9, ModelShowScale=10, ModelShowRot=11, }
local commonData = {{0.05, 0.11, 0, }, {0.65, 0.65, 0.65, }, {0, -23.08, 0, }, {-0.02, 0, -1.28, }, {0.6, 0.6, 0.6, }, {0, 0, 0, }, {0.03, 0.03, -0.71, }, {0.8, 0.8, 0.8, }, {0, 16.6, 0, }, {0.01, 0.15, 0, }, {0.4, 0.4, 0.4, }, {0.15, -0.2, 0, }, {0.25, 0.25, 0.25, }, {0, -32.8, 0, }, {-0.13, 0.16, -1.7, }, }
local config = {
{1, 2700011, 5, 1, "str_monster_name_2700011", "str_monster_des_2700011", "2700011_icon", commonData[1], "body_atk_idle", commonData[2], commonData[3], },
{2, 2700021, 4, 1, "str_monster_name_2700021", "str_monster_des_2700021", "2700021_icon", commonData[4], "body_atk_idle", commonData[5], commonData[6], },
{3, 2700041, 6, 1, "str_monster_name_2700041", "str_monster_des_2700041", "2700041_icon", commonData[7], "body_atk_idle", commonData[8], commonData[9], },
{4, 2700031, 3, 1, "str_monster_name_2700031", "str_monster_des_2700031", "2700031_icon", commonData[10], "body_atk_idle", commonData[11], commonData[6], },
{5, 2800051, 1, 3, "str_monster_name_2800051", "str_monster_des_2800051", "2800051_icon", commonData[12], "body_atk_idle", commonData[13], commonData[14], },
{6, 2800061, 2, 2, "str_monster_name_2800061", "str_monster_des_2800061", "2800061_icon", commonData[15], "body_atk_idle", commonData[13], commonData[6], },
[11]={11, 2710011, 5, 1, "str_monster_name_2710011", "str_monster_des_2710011", "2700011_icon", commonData[1], "body_atk_idle", commonData[2], commonData[3], },
[12]={12, 2710021, 4, 1, "str_monster_name_2710021", "str_monster_des_2710021", "2700021_icon", commonData[4], "body_atk_idle", commonData[5], commonData[6], },
[13]={13, 2710041, 6, 1, "str_monster_name_2710041", "str_monster_des_2710041", "2700041_icon", commonData[7], "body_atk_idle", commonData[8], commonData[9], },
[14]={14, 2710031, 3, 1, "str_monster_name_2710031", "str_monster_des_2710031", "2700031_icon", commonData[10], "body_atk_idle", commonData[11], commonData[6], },
[15]={15, 2710032, 3, 1, "str_monster_name_2710032", "str_monster_des_2710032", "2700031_icon", commonData[10], "body_atk_idle", commonData[11], commonData[6], },
[16]={16, 2710033, 3, 1, "str_monster_name_2710033", "str_monster_des_2710033", "2700031_icon", commonData[10], "body_atk_idle", commonData[11], commonData[6], },
[17]={17, 2810051, 1, 3, "str_monster_name_2810051", "str_monster_des_2810051", "2800051_icon", commonData[12], "body_atk_idle", commonData[13], commonData[14], },
[18]={18, 2810061, 2, 2, "str_monster_name_2810061", "str_monster_des_2810061", "2800061_icon", commonData[15], "body_atk_idle", commonData[13], commonData[6], },
[19]={19, 2810062, 2, 2, "str_monster_name_2810062", "str_monster_des_2810062", "2800061_icon", commonData[15], "body_atk_idle", commonData[13], commonData[6], },
[20]={20, 2720041, 6, 1, "str_monster_name_2710041", "str_monster_des_2720041", "2700041_icon", commonData[7], "body_atk_idle", commonData[8], commonData[9], },
[21]={21, 2820062, 2, 2, "str_monster_name_2820062", "str_monster_des_2820062", "2800061_icon", commonData[15], "body_atk_idle", commonData[13], commonData[6], },
[22]={22, 2730011, 4, 1, "str_monster_name_2730011", "str_monster_des_2730011", "2700021_icon", commonData[4], "body_atk_idle", commonData[5], commonData[6], },
[23]={23, 2730021, 3, 1, "str_monster_name_2730021", "str_monster_des_2730021", "2700021_icon", commonData[4], "body_atk_idle", commonData[5], commonData[6], },
[24]={24, 2730031, 5, 1, "str_monster_name_2730031", "str_monster_des_2730031", "2700021_icon", commonData[4], "body_atk_idle", commonData[5], commonData[6], },
[25]={25, 2730041, 3, 1, "str_monster_name_2730041", "str_monster_des_2730041", "2700021_icon", commonData[4], "body_atk_idle", commonData[5], commonData[6], },
[26]={26, 2730051, 6, 1, "str_monster_name_2730051", "str_monster_des_2730051", "2700021_icon", commonData[4], "body_atk_idle", commonData[5], commonData[6], },
[27]={27, 2730061, 6, 1, "str_monster_name_2730061", "str_monster_des_2730061", "2700021_icon", commonData[4], "body_atk_idle", commonData[5], commonData[6], },
}
return config, 'ID', key