---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Value=2, }
local config = {
["SequenceOccupancyTime"]={"SequenceOccupancyTime", "500", },
["SequenceOccupancyRandomRange"]={"SequenceOccupancyRandomRange", "1000", },
["DungeonWarningMaxY"]={"DungeonWarningMaxY", "2", },
["TeamButtonClickTime"]={"TeamButtonClickTime", "500", },
["TeamDefaultCameraPos"]={"TeamDefaultCameraPos", "0.354,-0.328,6.724", },
["TeamDefaultModelGrayParams"]={"TeamDefaultModelGrayParams", "0.02,0,1.8,0.7", },
["MonsterStayThrowIdleTime"]={"MonsterStayThrowIdleTime", "3000", },
["TriggerMergeBattleR"]={"TriggerMergeBattleR", "5", },
["InitiativeAttackBtText"]={"InitiativeAttackBtText", "str_ui_city_initiative_attack", },
["InitiativeAttackBtIcon"]={"InitiativeAttackBtIcon", "ui_fuben_xuanxiangicon_zhandou", },
["ExitBattleCameraCheck_RolePoints"]={"ExitBattleCameraCheck_RolePoints", "1;2", },
["LoadingRandomPics"]={"LoadingRandomPics", "ui_loading_beijing1,ui_loading_beijing2,ui_loading_beijing3,ui_loading_beijing4,ui_loading_beijing5", },
["LoadingRandomTxt"]={"LoadingRandomTxt", "str_ui_login_loading_tip1,str_ui_login_loading_tip2,str_ui_login_loading_tip3,str_ui_login_loading_tip4,str_ui_login_loading_tip5,str_ui_login_loading_tip6,str_ui_login_loading_tip7,str_ui_login_loading_tip8,str_ui_login_loading_tip9,str_ui_login_loading_tip10,str_ui_login_loading_tip11,str_ui_login_loading_tip12,str_ui_login_loading_tip13,str_ui_login_loading_tip14,str_ui_login_loading_tip15,str_ui_login_loading_tip16,str_ui_login_loading_tip17,str_ui_login_loading_tip18,str_ui_login_loading_tip19,str_ui_login_loading_tip20,str_ui_login_loading_tip21,str_ui_login_loading_tip22,str_ui_login_loading_tip23,str_ui_login_loading_tip24,str_ui_login_loading_tip25,str_ui_login_loading_tip26,str_ui_login_loading_tip27,str_ui_login_loading_tip28", },
["LoadingAcountNumLimit"]={"LoadingAcountNumLimit", "6", },
["BgmVolume"]={"BgmVolume", "0.5", },
["WaterMaName"]={"WaterMaName", "Water (Instance)", },
}
return config, 'ID', key