---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, BattleType=2, WaveList=3, BattleEnterTL=4, EnterPos1=5, EnterPos2=6, DeathTimeline=7, }
local commonData = {{-6.277319, 0, -11.07948, }, {3.183969, 0, -11.50642, }, }
local config = {
[124420000]={124420000, 1, {10000, }, nil, commonData[1], commonData[2], },
[124420001]={124420001, 1, {10001, }, nil, commonData[1], commonData[2], },
[124420002]={124420002, 1, {10002, }, nil, commonData[1], commonData[2], },
[124420003]={124420003, 1, {10003, }, nil, commonData[1], commonData[2], },
[124420004]={124420004, 1, {10004, }, nil, commonData[1], commonData[2], },
[124420005]={124420005, 1, {10005, }, nil, commonData[1], commonData[2], },
[124420007]={124420007, 1, {10006, }, nil, commonData[1], commonData[2], },
[124420008]={124420008, 1, {10007, }, nil, commonData[1], commonData[2], },
[124420009]={124420009, 1, {10008, }, nil, commonData[1], commonData[2], },
[124420010]={124420010, 1, {10009, }, nil, commonData[1], commonData[2], },
[124420013]={124420013, 1, {10010, }, nil, commonData[1], commonData[2], },
[124420014]={124420014, 1, {10011, }, nil, commonData[1], commonData[2], },
}
return config, 'ID', key