---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, WaveType=2, Enemy1=3, Enemy2=4, Enemy3=5, CameraCfgId=6, WaveCameraCfgId=7, OffsetPos1=8, OffsetPos2=9, OffsetPos3=10, OffsetEulerAngles1=11, OffsetEulerAngles2=12, OffsetEulerAngles3=13, TeamOffsetPos=14, TeamOffsetEulerAngles=15, WaveBuffList=16, }
local commonData = {{0, 180, 0, }, {-3.4, 0, 1.7, }, {-0.5, 0, 3.5, }, {2.3, 0, 2.1, }, {0, 0, 4.3, }, {-3.400002, 0, 1.699997, }, {2.299999, 0, 2.099998, }, }
local config = {
[41]={41, 1, -1, 200101, -1, 1, 0, {-3.400017, 0, 1.699982, }, {-0.5000257, 0, 3.499997, }, {2.299995, 0, 2.100013, }, commonData[1], commonData[1], commonData[1], {-2.161786E-05, 0, 4.3, }, commonData[1], },
[51]={51, 1, 200201, -1, 200202, 1, 0, commonData[2], commonData[3], commonData[4], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[61]={61, 1, 200501, -1, 200501, 1, 0, commonData[2], commonData[3], commonData[4], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[71]={71, 1, -1, 200401, -1, 1, 0, commonData[2], commonData[3], commonData[4], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[81]={81, 1, -1, 200701, -1, 2, 0, {-3.400013, 0, 1.699982, }, {-0.5000181, 0, 3.499997, }, {2.299987, 0, 2.100013, }, commonData[1], commonData[1], commonData[1], {-2.543256E-05, 0, 4.3, }, commonData[1], },
[91]={91, 1, 200801, 200801, 200801, 1, 0, commonData[2], commonData[3], commonData[4], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[92]={92, 1, 200801, 200802, 200801, 1, 0, commonData[2], commonData[3], commonData[4], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[101]={101, 1, -1, 200901, -1, 1, 0, commonData[2], commonData[3], commonData[4], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[111]={111, 1, 201001, -1, 201001, 1, 0, commonData[2], commonData[3], commonData[4], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[121]={121, 1, 201101, 201101, 201101, 1, 0, commonData[2], commonData[3], commonData[4], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[131]={131, 1, 200301, -1, 200301, 1, 0, commonData[2], commonData[3], commonData[4], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[141]={141, 1, -1, 200601, -1, 1, 0, commonData[2], commonData[3], commonData[4], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[151]={151, 1, 201202, -1, 201201, 1, 0, {-3.400012, 0.2291489, 1.699982, }, {-0.5000181, 0, 3.499999, }, {2.299992, 0.2265015, 2.100013, }, commonData[1], commonData[1], commonData[1], {-2.461299E-05, 7.629395E-06, 4.3, }, commonData[1], },
[161]={161, 1, 201301, -1, 201301, 1, 0, commonData[2], commonData[3], commonData[4], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[171]={171, 1, 201401, 201402, 201403, 1, 0, commonData[2], commonData[3], commonData[4], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[181]={181, 1, -1, 201501, -1, 1, 0, commonData[2], commonData[3], commonData[4], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[191]={191, 1, 201502, 201501, 201503, 1, 0, commonData[2], commonData[3], commonData[4], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[201]={201, 1, 201701, 201702, 201703, 1, 0, commonData[2], commonData[3], commonData[4], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[211]={211, 1, 201801, -1, 201802, 1, 0, commonData[2], commonData[3], commonData[4], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[221]={221, 1, 200102, -1, -1, 1, 0, commonData[2], commonData[3], commonData[4], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[231]={231, 1, -1, 201901, -1, 3, 0, {-3.400017, 0, 1.699983, }, {-0.5000258, 0, 3.499995, }, {2.299995, 0, 2.100016, }, commonData[1], commonData[1], commonData[1], {-2.161227E-05, 0, 4.300001, }, commonData[1], },
[241]={241, 1, 202001, 202001, 202001, 1, 0, commonData[2], commonData[3], commonData[4], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[242]={242, 1, 202001, 202002, 202001, 1, 0, commonData[2], commonData[3], commonData[4], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[1008001]={1008001, 1, 203002, 202002, 203003, 1, 0, commonData[6], commonData[3], commonData[7], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[1008002]={1008002, 1, 203002, 203001, 203003, 1, 0, commonData[6], commonData[3], commonData[7], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[1008101]={1008101, 1, 203002, 202002, 203003, 1, 0, commonData[6], commonData[3], commonData[7], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
[1008102]={1008102, 1, -1, 200401, -1, 1, 0, commonData[6], commonData[3], commonData[7], commonData[1], commonData[1], commonData[1], commonData[5], commonData[1], },
}
return config, 'ID', key