---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, BattleType=2, WaveList=3, BattleEnterTL=4, EnterPos1=5, EnterPos2=6, DeathTimeline=7, }
local commonData = {{0, 0, 0, }, {-1.525879E-05, 0, 0, }, }
local config = {
[4]={4, 1, {41, }, nil, {162.602, 10, 33.04947, }, {156.3526, 10, 32.93085, }, },
[5]={5, 2, {51, }, nil, commonData[1], commonData[1], },
[6]={6, 2, {61, }, nil, commonData[1], commonData[1], },
[7]={7, 2, {71, }, nil, commonData[1], commonData[1], },
[8]={8, 3, {81, }, "SpecialPerformanceTL", commonData[1], commonData[1], },
[9]={9, 2, {91, 92, }, nil, commonData[1], commonData[1], },
[10]={10, 2, {101, }, nil, commonData[1], commonData[1], },
[11]={11, 2, {111, }, nil, commonData[1], commonData[1], },
[12]={12, 2, {121, }, nil, commonData[1], commonData[1], },
[13]={13, 2, {131, }, nil, commonData[1], commonData[1], },
[14]={14, 2, {141, }, nil, commonData[1], commonData[1], },
[15]={15, 3, {151, }, "SpecialPerformanceTL", commonData[1], commonData[1], },
[16]={16, 2, {161, }, nil, commonData[1], commonData[1], },
[17]={17, 2, {171, }, nil, commonData[1], commonData[1], },
[18]={18, 2, {181, }, nil, commonData[1], commonData[1], },
[19]={19, 2, {191, }, nil, commonData[1], commonData[1], },
[20]={20, 2, {201, }, nil, commonData[1], commonData[1], },
[21]={21, 2, {211, }, nil, commonData[1], commonData[1], },
[22]={22, 2, {221, }, nil, commonData[1], commonData[1], },
[23]={23, 3, {231, }, "SpecialPerformanceTL", commonData[2], commonData[2], "tl_0602_210000023_01", },
[24]={24, 2, {241, 242, }, nil, commonData[1], commonData[1], },
[100800]={100800, 1, {1008001, 1008002, }, nil, commonData[1], commonData[1], },
[100810]={100810, 1, {1008101, 1008102, }, nil, commonData[1], commonData[1], },
}
return config, 'ID', key