---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Control=2, Cond=3, }
local config = {
{1, 1, "type :1", },
{2, 1, "type :2,target:10", },
{3, 0, "type :2,target:100", },
}
return config, 'ID', key