---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, BhvType=2, Param1=3, Param2=4, }
local config = {
[10201001]={10201001, 1, "100010", "1", },
}
return config, 'ID', key