---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, EventID=2, EventPos=3, TaskTitle=4, TaskContent=5, TaskPillar=6, TaskRout=7, IsShowDistance=8, }
local commonData = {{138.09, 32, -43.25, }, }
local config = {
{1, 100010, nil, nil, nil, nil, nil, true, },
{2, 100020, {159.59, 10, 17, }, "str_ui_city_temp_task_title101", "str_ui_city_temp_task_content101", true, true, true, },
{3, 100360, {159, 10, 7.35, }, "str_ui_city_temp_task_title101", "str_ui_city_temp_task_content101", true, true, true, },
{4, 100370, commonData[1], "str_ui_city_temp_task_title101", "str_ui_city_temp_task_content102", nil, nil, true, },
{5, 100420, commonData[1], "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content103", nil, nil, true, },
{6, 100560, nil, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content105", nil, nil, true, },
{7, 100650, {88.94, 11.18, -60.95, }, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content105", nil, nil, true, },
{8, 100410, nil, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content105", nil, nil, true, },
{9, 100670, nil, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content105", nil, nil, true, },
{10, 100060, {80.6, 1, 3.29, }, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content105", nil, nil, true, },
{11, 100660, nil, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content106", true, true, true, },
{12, 100680, nil, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content106", true, true, true, },
{13, 100570, nil, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content106", nil, nil, true, },
{14, 100320, {31.34, 18.59, 18.85, }, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content107", nil, nil, true, },
{15, 100330, {26.08, 18.97, -16.64, }, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content107", nil, nil, true, },
{16, 100580, nil, "str_ui_city_temp_task_title102", "str_ui_city_temp_task_content108", nil, nil, true, },
{17, 100380, {-43.9, 1, -23.99, }, "str_ui_city_temp_task_title103", "str_ui_city_temp_task_content109", nil, nil, true, },
{18, 100690, nil, "str_ui_city_temp_task_title103", "str_ui_city_temp_task_content110", nil, nil, true, },
{19, 100720, {-27.56, 1.72, 12.31, }, "str_ui_city_temp_task_title103", "str_ui_city_temp_task_content110", nil, nil, true, },
{20, 102010016, nil, "str_ui_city_temp_task_title103", "str_ui_city_temp_task_content110", nil, nil, true, },
{21, 100390, {-63.57, 13, -20.9, }, "str_ui_city_temp_task_title103", "str_ui_city_temp_task_content110", nil, nil, true, },
{22, 100730, nil, "str_ui_city_temp_task_title103", "str_ui_city_temp_task_content111", nil, nil, true, },
{23, 100640, nil, "str_ui_city_temp_task_title103", "str_ui_city_temp_task_content111", nil, nil, true, },
{24, 100430, {-50, 57.3, -40, }, "str_ui_city_temp_task_title104", "str_ui_city_temp_task_content112", nil, nil, true, },
{25, 100700, nil, "str_ui_city_temp_task_title104", "str_ui_city_temp_task_content113", nil, nil, true, },
{26, 100710, nil, "str_ui_city_temp_task_title104", "str_ui_city_temp_task_content113", nil, nil, true, },
{27, 102010015, {62.86, 67.17, -131.05, }, "str_ui_city_temp_task_title104", "str_ui_city_temp_task_content113", nil, nil, true, },
{28, 100590, nil, "str_ui_city_temp_task_title104", "str_ui_city_temp_task_content113", nil, nil, true, },
{29, 100600, {149.7, 56.61, -146.03, }, "str_ui_city_temp_task_title104", "str_ui_city_temp_task_content114", nil, nil, true, },
{30, 100610, nil, "str_ui_city_temp_task_title104", "str_ui_city_temp_task_content115", nil, nil, true, },
{31, 100620, nil, "str_ui_city_temp_task_title105", "str_ui_city_temp_task_content116", nil, nil, true, },
{32, 100540, nil, "str_ui_city_temp_task_title105", "str_ui_city_temp_task_content117", nil, nil, true, },
}
return config, 'ID', key