---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, CameraBlendTime=2, CameraPauseTime=3, CameraTargetPos=4, CameraTargetEuler=5, CameraTargetFOV=6, }
local config = {
[10001]={10001, 1, 2, {58, 15.17, -56.76, }, {15, 35, 0, }, },
[10002]={10002, 2, 2, {34.98, 8.23, 49.84, }, {20, 210, 0, }, },
[102010017]={102010017, 2, 2, {147.4771, 14.01, 69.47038, }, {10.07229, 268.9656, -0.0003824079, }, },
[102010018]={102010018, 3, 2, {69.1636, 15.36959, -60.35893, }, {15.05706, 35.47672, 0.001013653, }, },
}
return config, 'ID', key