---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, AffectBehaviorType=2, AffectTargetType=3, AffectTargets=4, AffectBehaviorParam=5, AffectNum=6, }
local config = {
[21000001]={21000001, 1, 1, {"23_231_201901", }, "-0.25", },
[10201002]={10201002, 2, 2, nil, "20000003", 1, },
[10201003]={10201003, 2, 4, nil, "20000004", 1, },
[10201004]={10201004, 2, 2, nil, "20000005", 1, },
[10201005]={10201005, 2, 2, nil, "20000006", 1, },
[10201006]={10201006, 2, 4, nil, "20000007", 1, },
}
return config, 'ID', key