---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, WaveType=2, Enemy1=3, Enemy2=4, Enemy3=5, ExtraEnemy=6, CameraCfgId=7, WaveCameraCfgId=8, OffsetPos1=9, OffsetPos2=10, OffsetPos3=11, OffsetEulerAngles1=12, OffsetEulerAngles2=13, OffsetEulerAngles3=14, TeamOffsetPos=15, TeamOffsetEulerAngles=16, WaveBuffList=17, }
local commonData = {{0, 180, 0, }, }
local config = {
[10000]={10000, 2, -1, 100103, -1, {100102, 100105, }, 0, 0, {-3.400002, 0, 1.699997, }, {-0.5, 0, 3.5, }, {2.299999, 0, 2.099998, }, commonData[1], commonData[1], commonData[1], {0, 0, 4.3, }, commonData[1], },
}
return config, 'ID', key