---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, EventType=2, EventTriggerType=3, Des=4, CorrelationIDs=5, EventTriggerConditionGroupID=6, EventActiveConditionGroupID=7, EventCompleteConditionGroupID=8, MapElementID=9, EventReward=10, ForcedShow=11, }
local config = {
[124440000]={124440000, 1, 1, "dwad", 0, nil, nil, nil, 0, nil, false, },
[124440001]={124440001, 2, 1, "dawd", 124440001, nil, nil, nil, 0, nil, false, },
}
return config, 'ID', key