---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, InteractObjectType=2, CanPerception=3, PrefabName=4, EffectName=5, EnterBehavior=6, CompleteBehavior=7, TargetState=8, IsInScene=9, }
local config = {
[102020010]={102020010, 3, false, "common_heal_box", "fx_p_Interaction", nil, {10001, 10002, }, 0, false, },
[102020011]={102020011, 1, false, "interact_p_baoxiang_02", nil, nil, {10004, }, 0, false, },
[102020024]={102020024, 3, false, "common_heal_box", "fx_p_Interaction", nil, {10005, 10006, }, 0, false, },
[102020031]={102020031, 3, false, "common_heal_box", "fx_p_Interaction", nil, {10007, 10008, }, 0, false, },
[102020038]={102020038, 3, false, "common_heal_box", "fx_p_Interaction", nil, {10009, 10010, }, 0, false, },
[102020045]={102020045, 3, false, "common_heal_box", "fx_p_Interaction", nil, {10011, 10012, }, 0, false, },
[102020071]={102020071, 4, false, "interact_p_baoxiang_02", nil, {10013, }, nil, 0, false, },
[102020072]={102020072, 4, false, "interact_p_baoxiang_02", nil, {10014, }, nil, 0, false, },
[102020073]={102020073, 4, false, "interact_p_baoxiang_02", nil, {10015, }, nil, 0, false, },
[102020074]={102020074, 4, false, "interact_p_baoxiang_02", nil, {10016, }, nil, 0, false, },
[102020075]={102020075, 3, true, "interact_p_baoxiang_01_m", "fx_p_Interaction_baoxiang_01_m", nil, {10018, }, 0, false, },
}
return config, 'ID', key