---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, InteractObjectType=2, CanPerception=3, PrefabName=4, EffectName=5, EnterBehavior=6, CompleteBehavior=7, TargetState=8, IsInScene=9, }
local config = {
[102500002]={102500002, 11, true, "Interact_p_ambortest", nil, nil, nil, nil, false, },
[102500003]={102500003, 11, true, "Interact_p_ambortest", nil, nil, nil, nil, false, },
}
return config, 'ID', key