---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, EventType=2, EventTriggerType=3, Des=4, CorrelationIDs=5, EventTriggerConditionGroupID=6, EventActiveConditionGroupID=7, EventCompleteConditionGroupID=8, MapElementID=9, EventReward=10, ForcedShow=11, }
local config = {
[102500000]={102500000, 1, 1, "出生点", 0, nil, nil, nil, nil, nil, false, },
[102500001]={102500001, 5, 2, "胜利点", 0, nil, nil, nil, nil, nil, false, },
[102500002]={102500002, 4, 3, "琥珀灯测试", 102500002, nil, nil, nil, nil, nil, false, },
[102500003]={102500003, 4, 3, "琥珀灯测试", 102500003, nil, nil, nil, nil, nil, false, },
}
return config, 'ID', key