---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, EventType=2, EventTriggerType=3, Des=4, CorrelationIDs=5, EventTriggerConditionGroupID=6, EventActiveConditionGroupID=7, EventReward=8, }
local config = {
[100010]={100010, 1, 1, "出生点", {0, }, },
}
return config, 'ID', key