---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, ElementType=2, CorrelationID=3, Des=4, }
local config = {
[100010]={100010, 1, 100011, "自动平台", },
[100020]={100020, 2, 1, "特殊区域", },
[100030]={100030, 3, 100031, "多阶段", },
}
return config, 'ID', key