---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, InteractObjectType=2, CanPerception=3, PrefabName=4, EffectName=5, EnterBehavior=6, CompleteBehavior=7, TargetState=8, IsInScene=9, }
local config = {
[112910004]={112910004, 1, false, "common_heal_box", "fx_p_Interaction", {10000, }, {10001, }, nil, false, },
}
return config, 'ID', key