---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, EventType=2, EventTriggerType=3, Des=4, CorrelationIDs=5, EventTriggerConditionGroupID=6, EventActiveConditionGroupID=7, EventCompleteConditionGroupID=8, MapElementID=9, EventReward=10, ForcedShow=11, }
local config = {
[112910000]={112910000, 8, 1, "daw", 112910000, nil, nil, nil, nil, nil, false, },
[112910001]={112910001, 9, 1, "daw", 112910001, nil, nil, nil, nil, nil, false, },
[112910002]={112910002, 9, 1, "daw", 112910002, nil, nil, nil, nil, nil, false, },
[112910003]={112910003, 2, 1, "daw", 112910003, nil, nil, nil, nil, nil, false, },
[112910004]={112910004, 4, 3, "dwqa", 112910004, nil, nil, nil, nil, nil, false, },
}
return config, 'ID', key