---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, Name=2, Desc=3, NeedMissionID=4, PlotID=5, }
local config = {
[4030001]={4030001, "str_mission_name_4030001", "str_mission_desc_4030001", 1, 2000101, },
[4030002]={4030002, "str_mission_name_4030002", "str_mission_desc_4030002", 2, 2000102, },
[4030003]={4030003, "str_mission_name_4030003", "str_mission_desc_4030003", 3, 2000102, },
}
return config, 'ID', key