---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {ID=1, EventType=2, EventTriggerType=3, Des=4, CorrelationIDs=5, EventTriggerConditionGroupID=6, EventActiveConditionGroupID=7, EventCompleteConditionGroupID=8, MapElementID=9, EventReward=10, ForcedShow=11, }
local config = {
[100120000]={100120000, 1, 1, "出生", 0, nil, nil, nil, 0, nil, false, },
[100120001]={100120001, 5, 2, "终点", 0, nil, nil, nil, 0, nil, false, },
}
return config, 'ID', key