---this config file was auto-generated by Excel2lua tool, do not modify it!

local key = {Id=1, Des=2, BuffId=3, LogicParam1=4, LogicParam2=5, LogicParam3=6, LogicParam4=7, LogicParam5=8, LogicParam6=9, LogicParam7=10, LogicParam8=11, LogicParam9=12, }
local config = {
[1001]={1001, "普攻加成", 20010, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
[1002]={1002, "大招加成", 20011, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
[1003]={1003, "返还ap", 20012, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
[1004]={1004, "返还cd", 20013, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
[1005]={1005, "返还能量", 20014, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
[1006]={1006, "提高充能", 20015, 0, 0, 0, 0, 0, 0, 0, 0, 0, },
}
return config, 'Id', key